# Preface and Life in the Zoo

## Preface

It was a chance encounter on a train to London that first made me think seriously about writing up some
of my life’s experiences. I was sitting opposite an American Lady who was on the staff of a magazine
and we started talking.

'Do you live in London?' she asked me.

'No, I live in a beautiful part of Northumberland, but I lived in London until I was twenty.'

'Oh, whereabouts did you live?'

How I replied to that question depended on whether I wanted to go on chatting. I could have just said 'In
North London', but instead I said that from the age of one to six we lived in Regent's Park before moving
to NW2.

'Whereabouts in Regent's Park' she asked. I then explained how when I was just a year old my father
returned from Africa to take up a post with grand sounding title of Superintendant of London Zoo, and
that our house was actually in the middle of the zoo itself.

She was incredulous but started asking me how much I could remember about my life in the zoo. 'Well
to be honest, I can remember a lot, as if it was just yesterday in fact.' It was then as we talked she started
saying what a wonderful story it could make. Curiously it was a few years before the rather bizarre story
The life of Pi was published, but I did admit it was the most wonderful environment for a small child to
grow up in. I can trace my interest in animals and the natural environment to those early years and didn't
even mind the taunts of my school friends about living in the monkey house. I put them down to
jealousy.

David, my brother is two years older than me, so after he started school I was on my own at home. I'm
pretty sure if my mother was to have done today what she did then she would have been in big trouble
with Social Services, but she was happy for me to roam the zoo by myself on my tricycle during the
mornings, with a note pinned to my back saying "PLEASE SEND ME HOME AT 12'o Clock for LUNCH"

I came to no harm, or at least not very often. My trike had no brakes, and if you have ever been to
London Zoo you may remember how it is divided in two by a road (The Outer Circle). Two tunnels allow
the public to access both side of the zoo, so for me it was great sport to come round the corner, then
with legs off the pedals and wide apart, whizz down the tunnel at top speed. That was all very well until
one day I came round the corner to see the tunnel was full of people. I aimed for a small gap to the left -
see, I remember it well - but hit the concrete wall instead. Luckily the zoo's electric meat wagon came
upon me, scraped me up and to the first aid post.

Apparently apart from a bent nose, which I have to this day I was relatively unscathed.

* * *

Well, dear friends, that is my two penny worth for starters. If the bug gets me that might be all you'll ever
get, and I will forgive you for thinking 'thank goodness for that' but much as I love Bonny her
conversation is somewhat limited, so this project might keep me relatively sane.

## Life in the Zoo

Our house in the zoo, long since demolished, was between Regents Park’s Outer Circle and the Regent’s
Canal. From my bedroom window I looked down on the canal, which was still in commercial use, and
can clearly remember horse drawn barges. Beyond the canal was Primrose Hill and to the left a white
block of flats which are still there in Ormonde Terrace. - you can see them by using Street View on
Google Maps! I mention this because I named the flats The Teddies’ Gonking School. Now why might a
small child come up with that name? For a long time I could think of no logical answer, but then I
realised that when lying in bed I could often hear a dull thumping sound. It was my heart beating, but my
explanation was more imaginative. I could hear the teddies Gonking.

Lying in bed, in addition to the continuous gonking of the Teds, I could hear other sounds. The
Kookaburras were within earshot, and their call was the first bird sound I knew. Also known as the
Laughing Jackass, not a bad name for some people I know today, their distinctive cackle was loud and
clear. I could also hear the lions roaring at night. They didn’t worry me as much as the leopard I was
convinced lived under my bed. I had to turn out the light and leap onto the bed to stop it getting me.

I must have known the grounds better than most visitors, and on at least one occasion I was ‘found’ by a
well meaning member of the public who took me to the lost property office. I must have played along
with this, but that got me into trouble with father and I don’t think I did it again knowingly.

My favourite animals were Dixie, the female African Elephant, Prince, a beautiful Cheetah, and Rajah a
very tame tiger, who father would stroke through the bars. This did cause serious trouble when day
David and I climbed over the safety rail to get closer to Rajah. Too close! I don’t think we touched him,
but we had been seen by the head keeper. Later that day we were heading off for a family picnic, when
as luck would have it just as we were driving past the offices as the wretched man was crossing the
road. He flagged my father down and snitched on us. Perhaps he also saved our lives, but there was no
picnic that day.

Rats were a menace and a sixpence bounty was paid for any caught. Father had a shotgun and some
evenings we accompanied him on his rounds. He would shoot rats in the moats in front of the Mappin
Terraces. I had a swing in the garden and one day I washed it with a rag and a bucket of water. I didn’t
put the bucket away, but in the night a rat climbed into the bucket and drowned. Poor rat, but I was rich
with my sixpence.

World War II had only finished three years before we moved to the zoo. Rationing was still in force and
times were hard, so people had to make do as best they could. Unfortunately not everyone was honest,
and among the zoo staff there were opportunists who used their situations to their advantage.

As the public paid to come into the Zoo they moved through turnstiles which recorded the numbers
entering. It was cash only and this temptation was too much for some. At some point father realised that
the numbers coming into the zoo did not tally with the takings at the gates so he decided to investigate.
He soon learned that the turnstiles were far from foolproof, and offered several ways to be tricked. I
think he said in addition to one or two obvious techniques there were another half a dozen more subtle
ways to cheat. It was when father saw the man in charge of the gates coming to work by taxi, a luxury
out of the reach of his salary, that he had to act. Father would of course have known exactly how much
he was earning so he had the turnstiles removed and replaced by new Automaticket machines. (You
could buy a vintage one today on eBay for £200.)

There were other ‘rackets’, as father called them, rife in the zoo. A lot of food intended for the animals
ended up on dinner plates, but one ingenious scheme only came to light when he inspected the reptile
house late on night. As he went in he saw what he described as rafts of cockroaches on the floor.
Thousands of them! When he demanded action be taken to, suggesting poison, the objections by the
keepers was extreme. It turned out the cockroaches were being bred intentionally and sold to schools
and colleges for dissection in the biology lessons.

Stamping out these practices did not go down well with staff. They did not forget what he had done, so
when father’s post was abolished a few years later, despite a massive public outcry, they had their
revenge. More of this story in another chapter.

My first two posts were my childhood memories until I was six, but at this point I will answer a question
often asked "How did your father come to be given the post of running London Zoo."

The explanation I will give you could fill a book of its own. It is fascinating, but here is the short version.

My parents, George and Sheila met at Oxford University in the very early 1930's but they were from
entirely different backgrounds. My father's father was a clerk for a shipping company in the London
docks, my mother's grandfather had founded a large department store in Southsea, Handley's. At its
peak the store employed 500 staff, and something I found out only recently, when there as a local
airshow a company making kit planes approached Handley's offering them an agency for their planes.
My great grandfather must have a sense of humour, because in flyer (excuse the pun) for the store's
general products it included these words. "Also Airplanes, care of the Plumbing Department".

So, going back to my parents, they had met at University. My father studied Forestry, my mother History.
My father graduated in 1932 but it was during depths of the depression. (Sounds familiar?) Most of the
forestry graduates would have expected to get jobs with the Colonial Service in either Africa, or Asia,
but in 1932 there were NO jobs on offer. None. Father did a one year research degree studying the
Classification of the Black Poplars, really exciting stuff, but it gained him an FLS (Fellow of the Linnean
Sociiety). The following year there were four posts advertised by the Colonial Service for forestry, but by
then there were graduates from two years from four universities after them. In addition to Oxford,
Edingburgh, London and Bangor offered degrees in forestry.

Father had spent at least one summer in Germany and had learned German, and he believes it was this
which clinched the job for him.

So in 1934 a 25 year old George Cansdale headed off for West Africa, destination the Gold Coast, now
Ghana.

For a young man whose interest was natural history, to be spending his working life in the tropical rain
forest was heaven. Unlike East Africa, with its large game parks, the West African wildlife was much less
known, so father was in his element studying and collecting animals. His particular interests became
small mammals and reptiles.

For years his day job was conducting surveys of the forest, identifying the types, quantities and maturity
of the different commercial tree species, This involved trecking out into the forest for about three weeks
at a time, but this gave him an excellent opportunity to collect animals. Soon after arriving he had got to
grips with the local language 'Twi'. (The T pronounced 'ch', so "Chwee".) He remained fluent for the rest
of his life and on several occasion in London when he spotted someone who he could tell was Ghanaian
he would ask they where they came from. If, as he correctly suspected, they where native Twi speakers,
he would reduce them to either hysterics or tears when the started speaking together in Twi. Once he
was on a bus sitting behind two ladies speaking Twi. As he got up to leave he leant forwards and said
quietly "Be careful what you say, you never know who might be listening."

I must tell you about a funny incident I once had. A few years ago I was in London with Sue attending a
Transplant conference at Church House in Westminster. Afterwards we took the opportunity to visit the
House of Parliament. It was mid December.

I guessed that the lift attendant was West African. He confirmed that he was indeed. Ghanaian. I only
know two or three Twi expressions, 'Mi num' which means 'i drink', and 'Mi num' which means 'I don't
drink'. Hold on, aren't they the same words? Exactly! It is a tonal language, so the slightest difference in
tone is needed to distinguish them.

My third expression is 'Afrishiapa madam foo' which as it happens means 'Happy Christmat my friend.'
The lovely lift attendant was gob smacked when I wished him Happy Christmas in his own language, but
disappointed that was virtually all the Twi I knew, but then was amused when I told him I was 'made in
Ghana'. "So you are an African!" he told me.

I'm afraid this chapter is going to be quite long, especially if i am going to digress, so i am taking a break
now.

* * *

Today looks like serious lock down. Hang on in there lovely people. Phone someone you've not been in
touch with over your morning coffee.

Good morning all. Nationally we are now in virtual lock-down. We are facing a crisis at so many levels,
nationally certainly. For most of us in the UK we are facing a personal crisis too. Everything we took for
granted has been pulled from under us. We are facing a time a uncertainty the likes of which most of us
under 75 have never experienced.

The story I have started to tell in these pages will include incidents in my life which ranged from the
hilarious to the tragic. Like many of us, I have experienced the highs and lows of human existence. I am
sure in the future we will be asked how we coped.

This morning I will be talking about my father's time in West Africa. He left England in 1934 having fallen
in love with my mother. It was the time of great depression. A time of massive uncertainty. He was
setting off for an area known as 'The White Man's Grave', leaving the love of his life behind. Before long
Europe would be in turmoil and another World War would be on the horizon. Yet he coped. My own
father overcame all those challenges. I find that so very inspiring, so today I hope his story will
encourage all of us to ask ourselves how we can make the best of this wretched situation and come out
stronger at the other end.

In the 1930's the Gold Coast, now Ghana, was a British colony. I am conscious of fact that the history of
Europe's colonial past is extremely controversial and was not all good. But it was not all bad either, and
many times my father told me how he saw his role as helping to set up a sustainable forestry industry
which would stand the county in good stead when it became independent.

That is all I will say about that subject. My story is about the personal experience of one very junior
forester, just 25 years old, starting a new career in a foreign country, where many of known for the
diseases, could kill you, with constant high temperatures and high humidity. Sounds really inviting,
doesn't it.

The question was, what had attracted my father to a career in forestry? The answer was simple. He loved
wildlife and natural history. He had grown up in Essex and from an early age learned all the bird songs.
He fished, and one one occasion saved a young otter from irate fishermen intent on killing it, so I am
certain he was looking forward to studying the local wildlife.

His forest survey work presented a golden opportunity for this and the technique he developed was pure
genius. When setting off for a survey, often for tree weeks at a time and on foot with a team of local
bearers carrying all the equipment, the route would take him through a series of villages. As he reached
a village he would say to the chief, "Please tell your hunters, farmers and small boys, (and I'm sure small
girls too), that I will be coming back in about two weeks, and will pay for any animals they find. I will pay
more than they would receive if they sold them for chop (food), and I will pay more for them if they are
alive, and not dead."

This was a perfect plan and soon his reputation started to grow. Back at his house he was building up a
collection of animals, bur which I mean small mammals and reptiles. I don't know how or when his
interest in snakes began, but in time he became the leading expert in West African snakes.

This might interest you. Go into Ebay now and in the search bar type just one word... 'Cansdale'. Tick 'All
categories' an tick the little box which says 'Include Description'. See how many animal books pop up,
and note the author.

Anyway, back to George's story. As his reputation for his interest in animals grew, so more people would
seek him out and bring him specimens, and so his collection grew. Long before the wars in the former
Yugoslavia broke out he told me how he had a nick-name for a particular species of ground squirrel.

Unlike most of the other animals who coexisted quite happily with their own kind, these squirrels
constantly fought. He called them 'The Balkans' As a child I had no idea what this meant, but how true
that was!

Before I take a break, let me tell you one of my favourite stories. Before I do I must explain a bit about
Pidgin English. In areas where there are many different languages, one language tends to become the
main trading language spoken as a second language by people whose mother tongues were the minor
languages. So for example, in East Africa Swahili is the main trading language, whilst in northern
Nigeria, Niger and Chad, Hausa is the equivalent Elsewhere in north Africa it is Arabic.

In West Africa Pidgin English is still the common dialect in Ghana, Sierra Leone, Liberia and southern
Nigeria. Nowadays many only speak Pidgin, but those with a good education speak perfect English, but
equally can speak Pidgin too. It is a wonderful variety of English with its own grammar and use of
words. From my childhood I had heard my father tell wonderful stories in Pidgin, so by time I first went
to Africa I was already quite familiar with it and soon picked it up.

So this gives me an opportunity to tell you the first Pidgin English story.

My father just returned from an exhausting trek. He was tired, hungry and dirty and all he wanted to do
was have a bath and go to bed, but his steward called out to him.

"Massa, der be man here for door. He has fowl. Make you come lookum."

(Posh translation. 'Sir, there is a gentleman at the front door. He is holding a bird/chicken. Would you be
kind enough to come and see it?) Editor's note. I prefer the Pidgin version.

Father. 'Sorry, I'm very tired. I going to have a bath, please thank him but say not today'.

Steward. 'Massa, dees fowl be beeg fowl. Make you come lookum. ( I think you are getting hang of it
now.)

Father. Sorry, I don't mind how big it is. Please say not today!'

Steward. 'But Massa, dees fowl he be beeg pass all fowl.Make you come lookum!'

At this point my father had not alternative but to go and investigate. There at door was a man holding a
piece of string, attached to which, if you haven't guessed, was an OSTRICH.

TO BE CONTINUED.......

Enjoy your day dear friends. Phone a friend. Support someone who is feeling low, or think about writing
up your story for your grand kids.

Just a quick note before I start writing today. As from today I will also post these ramblngs on the 'Your
Story' page. Please don't feel you need to read all, or even any of these stories. I am pleased that a few
of you are finding them interesting, but at the end of the exercise they might, just might, be pulled
together into a single ebook. All you are getting for now are my thoughts as they spill onto the page,
bypassing the brain.

I hope you too are finding ways to cope with the Self Isolating message. This is helping me. So here
goes,

George threw himself into his forestry work and soon learned the local language, Twi He would proudly
tell me that he was the first European to learn it to translator standard. This greatly assisted his ability to
learn about the wildlife in the forests from the local people.

Over next few years built up a collection of live animals, recorded as many mammals and reptiles as he
could and even discovered half a dozen new species or sub species as yet not known to science. These
included Mrs. Cansdale's Bat, and the unromantic sounding Cansdale's Swamp Rat.

Some 40 years after leaving Ghana George was speaking to a Rotary club in York when after the talk a
Rotarian came up to him and said 'Mr. Cansdale, when I worked in Ghana I lived in the house you had
lived in.' When father asked how he knew that he was surprised by the answer.

'When I was allocated the house several people told me how lucky I was to have it. I asked why and was
told 'Many years ago a man lived in that house who had power over the snakes. His spirit is still there so
thieves will not go there. " '

He had taken up his post in 1934, and every two years was able to come home on leave. My parents had
met at Oxford University but did not get married until September 1940. They were married in All Souls,
Langham Place on Saturday the 7th September. I mention this for two reasons. First, you have often
seen pictures of this church, possibly without knowing its name. It is the church alongside BBC
Broadcasting House with the ring of columns, and tall conical spire. It is often shown before or during
news programmes. It was designed by the architect Nash, along with many of the building in Regents
Park. The church was to play a big part in my parents' lives for many years.

The second reason I mention the date of the wedding was that 7th September 1940 was the first day of
the daylight blitz. As my parents traveled to Devon on the train for their honeymoon they remarked on
the sunset, until they realised they were looking EAST ...... at London burning!

After the wedding my father returned alone to Africa. He was never in the armed services other than the
equivalent of the Home Guard. His knowledge of German meant that he had to check the letters of
German Internees for compromising information. The only thing of interest he found was a blank note
book along with covering letter saying that in view of the shortage of paper at home, here is something
for you. His suspicions were aroused and he discovered the pages had been written with invisible ink,
giving details of shipping in Takoradi harbour.

He was in charge of one two platoons. During on exercise his platoon was to attack Government House,
the other platoon had to defend it. Did he commandeer an Ambulance, Dirty Dozen style? No, he used
the dust cart. Having washed it out first, he piled his platoon into the back and drove in through the
gates unchallenged.

During the war father's role was supervising workshops making furniture for the forces. Tables and
chairs and beds. He had a reputation for spotting disguised defects so he carried with him a hammer
with which he could reveal shoddy repairs with a well aimed tap. As he approached the cry would go up
"The lion is coming.The lion is coming." At the end of the war he was presented with a magnificent
traditional wooden stool fashioned as a lion.

My mother visited my father for two tours, first in 1943/4, and then in 1945/6.

Visiting Africa for the first time can be quite a culture shock, but one of the things my mother was not
expecting was to hear my father speaking Pidgin English to his staff.

"I don't mind you speaking in this funny way to your staff, but I hope you won't expect me to" she said to
him. My father told her not to worry, but a few days late his steward approached him looking very
concerned.

"What's the problem?" he asked, The reply was classic, especially considering my mother's education
and upbringing.

"Massa, dis missus, why she no speak proper? I no fit hear-um!"

The end of the war.

My paternal grandmother, was from a Paignton family in Devon and father had links with the Zoo. Along
with most European Zoos their animal collections had suffered during the war years so father arranged
a shipment of animals to Paignton Zoo. He also had contacts with London Zoo and I understand he also
sent a significant number of animals to them too. I don't know how many consignment he send to
London, but they included monkeys, snakes and other animals of interest, but clearly he impressed
them with both his knowledge of the animals he sent and the efficiency with which he sent them, so
when they were looking for someone to take up the post of Superintendent, responsible for the running
of the Zoo itself, they offered him the job.

He therefore resigned from the Colonial Service and in 1948 started his new job, and new career at
London Zoo. I was just one year old.

Before I pick up, a short comment on our present crisis.

Good morning dear friends. I wonder how many of you keep diaries? I would not consider myself to be
particularly disciplined, but from the time I was about ten years old I started keeping diaries. To start
with they were just single years, and the entries were pretty basic, but over the years I started to write up
a bit more.

I now keep FIVE YEAR diaries. I started a new one this year, but the first year is a bit dull. By the fifth
year you can look back over the previous four years and be reminded of events you might otherwise
have forgotten all about. It is a silly habit, but quite fun. The period we are now experiencing is the most
challenging most of us will ever have experienced.

As most of you will know Sue and I lost our most wonderful daughter Zoe in 1998 when she was 22. This
year will be 22 years since she died. And for me it is now two years since Sue died. We often said Zoe
would never have wished her loss to have destroyed our lives; likewise I know Sue felt the same.

I am so thankful that Sue did not have the additional worry of a pandemic for last few months of her life.
She had so many friends visit her during her last few weeks, and the last she did before she fell asleep
for the last time was to give an old school friend a massive smile.

I say this because we must be strong. We will all be tested, but for any of us who keep diaries, (and why
not start one today if you don't already?) when next year we read what we have written today, we will
think back and think "was it really like that?"

WELL ENOUGH RAMBLINGS, this leads me on nicely to conclude my father's time in Africa.

A few years ago I found my mother's five year diary covering the years 1942 to 1947. I didn't know she
had one, although it is about somewhere I can't put my finger on it right now, but one thing interested
me. Where were my parents nine months before I was born? So I looked up 13th June 1946.

It was clear they were in the Gold Coast, so I WAS made in Ghana, but better still, this is what she wrote.
"KING'S BIRTHDAY. HOLIDAY!"

My father not only enjoyed his time in Africa but he made such full use of it it puts me to shame. Long
before colour photography he took black and white photos of his animals and the life of the people. He
processed most of the photos himself and would tell me how difficult this was because of the constant
high humidity. Some of his pictures are archived with the Geographical Society's collections.

The Governor at the time, Sir Alan Burns, was also very interested in wildlife and they became friends.
This friendship, between a lowly forestry officer and the senior civil servant, and the head of the Colonial
Service in the country was resented by my father's bosses, and sometimes ruffled feathers, and might
have been the reason he liked the expression "Those that matter don't mind. Those that mind don't
matter."

In the following years I would learn how much he was respected by his African colleagues just as I know
how much he respected them. It was strange for me, because although I was 22 before I went to Africa
for the first time, and then had a total of 44 trips between 1969 and 2010, it almost felt like going home.
My father's experiences had rubbed off on me as a child and stood me in good stead when I started
working in African water development years later.

In the previous chapter I mentioned how my father sent many animals back to England after the war.
Thanks to a very timely reminder from my cousin Michael Cansdale, who was very close to my father
and went to the same college as him, I can tell you how he was able to do that.

This is Michael writing.........

"My uncle George Cansdale, was at St Edmund Hall, Oxford, from 1929 to 1934. In 1934 he joined the
Colonial Service and was immediately sent out, at the age of 24, to be a Forestry Officer in the Gold
Coast (now Ghana). He stayed there throughout the war when his role was to send timber back to Britain
and to the colonies for the war effort.

But, what was he to do with the extensive collection that he was building up? He got in touch with his
old University friend, Francis Finch, who was overseas freight manager for Imperial Airways and then
later BOAC. Whenever a plane landed at Accra with spare cargo space, Finch would arrange, pro bono,
that animals and reptiles (snakes in particular, and small animals like bushbabies) could be loaded on
board, and sent back to the London Zoo and other European zoos, whose stock had been depleted
during the war. (If only informal arrangements with airlines could be made so easily nowadays by
friendship with their senior staff!)

The direct result was that when in 1947 the Council of The London Zoological Society needed to appoint
a new Superintendent to run the Zoo, they head-hunted Cansdale, who they knew to be not only a
knowledgable naturalist but also a great supporter of and contributor to their collection.

As a boy I regularly stayed with him at the Superintendent's House in the Zoo grounds in Regent's Park.

Very quickly after his appointment at the Zoo he realised the potential publicity that could be obtained
for the Zoo by using radio and the new medium of television to show interesting animals, live, in the
studio. He became one of the best known presenters of wildlife programmes and items on British TV
between the 1950s and the 1980s, and made regular appearances on Children's Hour, and, for many
years, on Blue Peter. David Attenborough, who joined the BBC as a junior manager in 1952, and quickly
became involved in programmes from the London Zoo, has paid warm tribute to George Cansdale's
pioneering work in that field."

Dear friends,

before I continue with .....

THIRD CAGE ON THE LEFT, PAGE 4 part 2.

THE DUKE OF BEDFORD AND SOME FISHY TALES

I would just like to share some thoughts with you this Sunday morning.

The Corona virus news is getting grimmer every day, and is likely continue getting worse for a while yet.
A sister of one of my friends died of it last week, a close friend is recovering from it and a son of other
close friends has just contracted it.

Times are going to be very very hard in lots of ways.

We can all look back over our lives and remember the grimmest times we have gone through. 22 years
ago we lost our most wonderful, vibrant daughter, very suddenly. It was too dreadful for words, yet life
went on, and some positive things even came out of it.

Bad times are nothing new in the history of mankind. I fear as a civilisation we thought we were
somehow immune. We are not, and we are not as clever as we perhaps like to think we are.

In 1969 I spent several months on Lake Chad. This story will feature later in my ramblings. My only
companion was my 'boss', a woman twice my age who on top of serious 'gender identification' issues
was also suffering from PTSD. I was the constant target of her wrath. It was the most horrible experience
imaginable.

During that period I came across a text which helped me immeasurably, and helped me to survive. The
verse was from the New Testament, (Hebrews 12, v.11) It says......

"Now no chastening for the present seemeth to be joyous, but grievous: nevertheless afterward it
yieldeth the peaceable fruit of righteousness unto them which are exercised thereby."

That is the King James version. A more modern translation says....

"We don't enjoy being disciplined. It always seems to cause more pain than joy. But later on, those who
learn from that discipline have peace that comes from doing what is right."

For my twopenny worth I would like to offer my own translation.

"Times like this are absolute hell. But if we can endure them , and do what we have to do, when we
emerge at the other side we will have learned from them and be stronger as a result."

All I will add is that although those few months on Lake Chad was very grim time for me, ultimately the
experience had a massive positive influence on my life.

Sorry. I am meant to be getting on with my narrative, but I just wanted to share those thoughts with you.
I hope they offered you a little encouragement .

Love to you all.

Richard.

Back to the writing........ TTFN

Mr. Ezra and Mandarins.
So the story so far describes how George was able to use his time as a forest officer in the Gold Coast (Ghana)
to collect and study the local animals, and then after the Second World War how was helped by a friend send to
send a lot the animals back to England to restock, London and Paignton Zoos.
This led to an invitation to become Superintendent of the London Zoo in Regents Park.
For my older brother David and myself growing up in the zoo was amazing. It was our home because our house
was in the middle of the zoo. Our immediate neighbours were the hippos, then the giraffes beyond them.
Father was only 38 when he took up his post, and having just returned from fourteen years in Africa he had few
close friends near by, but he was befriended by a number of people who shared his interests.
Children are very accepting of the world around them, so to accompany our parents to lunch invitations was part
of the territory. We didn't ask questions; we just went. One regular invitation was to have lunch with a certain 'Mr.
Ezra', an elderly man who lived in Surrey. He was involved with the Zoo, and had a house near Cobham. A
mansion might be a more accurate description.
The lunches were formal with a capital F. The massive table was set out with the finest silver and glassware.
There were finger bowls and I lost count of the number of courses, served of course by the staff.
Mr. Ezra had a large estate, and after lunch we would walk in the grounds, except I would ride in Mr. Ezra's
invalid chair, crouching down at his feet. It was one of those old fashioned elongated chairs with large wheels at
the back and a single one out in front, and electrified. There we free living wallabies in the grounds, numerous
nest boxes my father checked for occupancy, but apart from that I knew very little else about Mr. Ezra.
Roll on sixty years and one day I am walking beside the burn when I am astonished to see the gaudiest of all the
ducks. A drake Mandarin Duck. (I will attach a picture of one, not one I took myself, so you can see what I
mean.)
Mandarin Ducks are Chinese and favoured by wild fowl collectors for their ponds. I suppose the Mandarin is the
equivalent of Koi Carp. But what was a Mandarin Duck doing in Hartburn? Funnily enough I had always thought
of Mandarin Ducks a being so over the top that they looked unnatural. Even artificial; but when I saw it in its
natural environment I saw how wonderful it looks.
I continued to see a single Mandarin drake for a few years, then a pair, and then a small flock of them. In 2018 I
saw sixteen together a couple of times, and last year my friend and neighbour Gary saw the mum with about a
dozen ducklings. This spring I have see a pair several times, but yesterday I saw just the drake four times. My
guess is the female is nesting somewhere. (Factoids. They nest in holes in trees. They nest late so often suffer
from a housing shortage so their populations only grow slowly, and are about the only non-native species in the
country which causes no environmental damage.)
I have now learned that there is a strong population of Mandarin ducks in the Kielder/Tarset area, One day,
returning from a day out at Kielder Dam I pulled over to allow some cars to pass where the road is close to the
North Tyne. As I glanced to my left I was astonished to see about 25 Mandarin Ducks sitting around on exposed
rocks on the river banks.
By now my curiosity was firmly aroused. Where did all these Mandarin Ducks come from?

Five minutes Googling and I had the answer. "Mandarin Ducks were first kept in this country by the eminent bird
collector Albert Ezra on his estate in Surrey, and the feral population originated from there."
As with so much Googling, you can't leave it there, so I then started probing deeper. Who was Mr. Ezra? Well it's
all out there for you to discover but I'll tell you what I found. Albert Ezra was born in 1872 in India. His mother
and wife were members of the Sassoon Family. Yes, they included Siegfried Sassoon. The Sassoon family were
very successful bankers in China and were known as the Rothschilds of the East.
Click on this link.. https://en.wikipedia.org/wiki/Alfred_Ezra
My memory is that he was just a very sweet old man.
In future chapters I will talk about some of the other characters I encountered.
Dark times for many. Stay strong. Keep a diary and write up your story for your kids and friends.

Dear friends,

THIRD CAGE ON THE LEFT, PAGE 4 part 2.

THE DUKE OF BEDFORD AND SOME FISHY TALES

Before I start I would just like to share some thoughts with you this Sunday morning.

The Corona virus news is getting grimmer every day, and is likely continue getting worse for a while yet.
A sister of one of my friends died of it last week, a close friend is recovering from it and a son of other
close friends has just contracted it.

Times are going to be very very hard in lots of ways.

We can all look back over our lives and remember the grimmest times we have gone through. 22 years
ago we lost our most wonderful, vibrant daughter, very suddenly. It was too dreadful for words, yet life
went on, and some positive things even came out of it.

Bad times are nothing new in the history of mankind. I fear as a civilisation we thought we were
somehow immune. We are not, and we are not as clever as we perhaps like to think we are.

In 1969 I spent several months on Lake Chad. This story will feature later in my ramblings. My only
companion was my 'boss', a woman twice my age who on top of serious 'gender identification' issues
was also suffering from PTSD. I was the constant target of her wrath. It was the most horrible experience
imaginable.

During that period I came across a text which helped me immeasurably, and helped me to survive. The
verse was from the New Testament, (Hebrews 12, v.11) It says......

"Now no chastening for the present seemeth to be joyous, but grievous: nevertheless afterward it
yieldeth the peaceable fruit of righteousness unto them which are exercised thereby."

That is the King James version. A more modern translation says....

"We don't enjoy being disciplined. It always seems to cause more pain than joy. But later on, those who
learn from that discipline have peace that comes from doing what is right."

For my twopenny worth I would like to offer my own translation.
