# The Duke of Bedford and George Cansdale

"Times like this are absolute hell. But if we can endure them , and do what we have to do, when we
emerge at the other side we will have learned from them and be stronger as a result."

All I will add is that although it was very grim time for me, those few months on Lake Chad ultimately
had a massive positive influence on my life.

Sorry. I am meant to be getting on with my narrative, but I just wanted to share those thoughts with you.
I hope they offered you a little encouragement .

Love to you all.

Richard.

So here we go.....

## The Duke of Bedford and Some Fishy Tales

My father had a number of hobbies. Sailing, which he was good at but seldom had a chance to enjoy.
Jam, marmalade and chutney making, which he was good at and did regularly, but also he was a keen
and competent fly fisherman.

Through the generosity and kindness of his friends and acquaintances he was often offered the chance
of some excellent trout and salmon fishing - at a time when there seemed to be plenty of fish in the
rivers.

As a boy I enjoyed fishing too, although nowadays I get more pleasure from fish-watching. (I will explain
how this works in a later chapter.)

Father met many interesting people through his work at London Zoo. Some became friends such as Mr.
Ezra. (Yesterday a friend told me how she was so fascinated about him that she Googled him and now
"knows all about him")

There was also an old lady I would love know more about, but despite my best Googling efforts, I cannot
find out anything about her. Miss Maud Nobel lived on the Camden Town side of Primrose Hill. When you
knocked on her door you might have thought it was Battersea Dogs home from the noise. The door
would be opened by her maid, but then the diminutive Miss Nobel would come down the passage
surrounded by a flock of about a dozen Pekinese, all yapping and skidding around her.

That was nothing compared with what was to come. Turn left into the large front room and you were
confronted by literally dozens of cages of parrots of every shape and size. At the time it was almost
impossible for an ordinary mortal to tell whether Amazon parrots were male or female, but Miss Nobel
was of the few people who apparently could. Some year later technology made it easy. An endoscope
was inserted down below and if there were ovaries, the bird was without doubt a lady! (They don't like it
up'em in Cpl. Jones' immortal words.)

But now we come to the Duke of Bedford.

I cannot remember ever meeting him, but he was a keen naturalist and ornithologist, and also happened
to own the Woburn Estate. If you are curious to know more about him just Google '12th Duke of
Bedford'.

No mention was ever made of Duke's involvement with far right politics but in 1953 I remember being
told he had died in a shooting accident. The story I was given was that a sparrow hawk was preying on
his free flying flock of Budgerigars and as he was climbing over a style with a loaded shotgun he ended
up shooting himself. That might have been easier for a six year old to accept than the full truth 'whatever
that was' as our heir to throne might say.

On the Woburn estate there are number of lakes, and one day my father took me out fishing on the
largest lake in front of the Abbey. I was only tiny, but the fish he caught seemed to be monsters, and
vicious. Years later my father told me they were Zander, also known as Pike-perch. Predatory and pretty
ferocious. They were interesting times.

Some time after this we went back to Woburn for an entirely different kind of fishing. In the Chinese
garden there was an ornamental pond teeming with large Golden Carp. We were setting off to catch a
dozen of them for another zoo. 'Where is the rod?' I asked my father. 'We don't need a rod, the fish are so
tame we just need my landing net' he replied.

This turned out to be a significant underestimation of their intelligence because as soon as the landing
net was deployed the fish kept their distance, despite being tempted by the last of our white bread bait.

So it was back to London and a return trip the following week, armed with a rod and line.

Never has fishing been so easy. The moment the bread touched the water a feeding frenzy occurred and
within no time had a dozen large fish in the tank of water we had in the back of the estate car.

However, among the massive carp there two tiny ones. Well, relatively tiny compared to the carp, maybe
about five or six inches long. David and I were told we could have them if we could catch them. This
proved to be challenging. We had to wait until they were well away from the monsters, then cast
accurately to give them a chance to take the bait. Time and again, just as the target fish was about to
take the bait a big one beat him to it. I cannot think of any other fishing experience when one was
annoyed to catch the larger fish. Finally we were successful and the two goldfish lived for many years in
a tank in our garden in London.

Another chapter on fish and fishing will have to wait.

This is George's obituary written by Biddy Baxter, Blue Peter's iconic editor for many years who knew
him very well.

Some of what is written you may have read before, but there are lot of other snippets worth learning
about.

Quite an inspiration I think you will agree.

George Soper Cansdale, zoologist and broadcaster: born Brentwoood, Essex 29 November 1909;
Colonial Forest Service, Gold Coast 1934-48; Superintendent, Zoological Society of London 1948-53;
married 1940 Margaret Sheila Williamson (died 1992; two sons); died Great Chesterford, Essex 24
August 1993.

FOR ANY child watching Blue Peter during the Sixties, Seventies and most of the Eighties, George
Cansdale was television's zoo man - the large, avuncular studio guest who would show the presenters
how to bath six-foot pythons, produce bush-babies from his trouser pockets and tarantulas out of his
turn-ups.

Children loved him because he was quirky, authoritative and uncondescending. Presenters from Valerie
Singleton and John Noakes to Sarah Greene, Simon Groom and Peter Duncan admired him as an expert
and a true professional. Cansdale was guaranteed to provide riveting viewing. If it crawled, slithered,
flew, climbed or swam, he would bring it to the studio. Often his fingers were ominously covered with
bloody bits of Elastoplast - he was intrepid when it came to handling the most dangerous animal and
could never quite understand when a presenter flinched as a snake lunged or an orang-utan bared its
teeth.

Generations of directors were kept on their toes because Cansdale, whose knowledge was vast, rarely
did the same thing in the same order twice. During the 'live' transmissions there would be agonised
cries: 'He's put the rat in the other pocket', or 'The skink's going up his trousers instead of down his
sleeve]' The production team may have been reduced to jelly, but Cansdale remained imperturbable.
Just what you would expect from a man who had flown from Singapore to London with poisonous
snakes in his pyjamas. 'They had to be kept warm, they were perfectly safe in my hand baggage,' he
pointed out.

George Cansdale was born in 1909 in Brentwood, Essex. The son of a clerk in a City shipping office, he
won a scholarship to Brentwood School. His chief interest as a boy was ornithology, but as a student at
St Edmund Hall, Oxford, reading for a forestry degree, he broadened his outlook and spent an extra
couple of years doing his B Sc, followed by training for the Colonial Service.

In 1934, he was appointed Forest Officer for the Gold Coast, which was where he started collecting
animals. It happened almost by chance. A friend working for Paignton Zoo begged him to bring home as
many specimens as he could, on his next leave. Because his forestry work was so time-consuming,
Cansdale, who was fluent in Tui, one of the main languages, enlisted the help of the local children he
knew at the big government school on his station. He improvised travelling boxes from old petrol tins
and their wooden containers and the 80 specimens included squirrels, hornbills, owls, touracos and
snakes. This was when he had what he later described as his only 'serious' accident with animals - the
first poisonous snake he had ever handled alive.

A boy brought him a small black snake held in the split end of a stick - not more than a third of a metre
long and thinner than a finger. Although Cansdale picked it up correctly, behind the head, it bit the top of
his left index finger. Unfortunately for him it was a burrowing viper - one of the very few snakes that
cannot be picked up by hand as its lengthy fangs can strike however it is held.

In spite of his cutting the bite, letting it bleed and applying a tourniquet, by nightfall the fingertip had
turned grey. Gradually it rotted off and the finger healed - nearly half an inch short. Cansdale felt he had

had a lucky escape and it certainly didn't put him off collecting. He built up his own small zoos at his
various jungle stations and they were so popular with the local inhabitants he had to fix regular opening
hours. Whole classes of small children used to visit from schools in the towns too; most of them were
seeing forest creatures alive for the first time in their lives.

Cansdale trained teams of boys to help him collect live specimens for zoos abroad and also to prepare
skins for museums. They recorded many 'firsts' for West Africa, including two new species, a bat and a
flying squirrel, eight snakes not previously recorded for the Gold Coast, and a huge black cobra found in
a heap of rubbish in the office yard 8ft 8in long - nearly a foot longer than the previous best for West
Africa. As well as supplying London Zoo he was able to offer animals to the Dublin and Edinburgh Zoos
when they were restocking after the Second World War.

In 1940, George Cansdale married Sheila Williamson, who had been a fellow-student at Oxford, and thus
began a perfect partnership that lasted almost 52 years. They first met in 1933 and as well as a mutual
interest in wildlife they were both committed Christians. Sheila led a Bible study group for 30 years after
returning to the UK and from 1950 to 1971 George was Churchwarden of All Souls' Langham Place. A
Vice-President of the evangelical Crusaders Union, he spoke frequently at Crusader classes, churches
and other Christian groups - often accompanied by Percy and Polly, his pet python and bush-baby.

It was while he was home on leave in 1947 that George Cansdale was headhunted by the Zoological
Society of London. He was asked if he would take over as Superintendent from Dr Gwynne Vevers, who
was about to retire. It was an inspired choice, for, in addition to his lifelong study of animals, as a Forest
Officer Cansdale had added accounting, publicity, staff management, building, roadmaking and the care
of trees to his skills. He held this post for five years from May 1948, but they were far from happy ones.
He was quick to discover a hornet's nest of mismanagement and dishonesty and his efforts to stop the
malpractices met with robust opposition from nearly all quarters.

His detective work began with the turnstile staff. He soon realised their style of living was vastly above
their weekly wage packets. One man had a palatial house in Bedford and would take taxis to and from
the station to the zoo. Cansdale estimated at least 10 per cent of London Zoo's income was being fiddled
away by the turnstile cheats. When he changed the system there was an uproar.

On querying bills for the animals' food he discovered most of the keepers thought taking home bags full
of fresh fruit and vegetables a legitimate perk. One man even had a profitable line in selling off the zoo's
bedding- out plants - he supplied the best fuchsias in Camden and made a considerable income.

One of Cansdale's most extraordinary pieces of detection happened quite by chance. He was very much
a 'hands on' Superintendent, spending just as much time out and about in the zoo as in his office. Late
one night he decided to visit the reptile house. It was pitch dark and when he switched on the light he
discovered the whole floor area obliterated by a seething mass of cockroaches. Appalled by this lack of
hygiene he ordered an immediate de-infestation. To his amazement the keepers objected to any kind of
clean-up. 'Oh well,' he was eventually told by the one security officer who was on his side, 'they're
selling 'em for sixpence each]' The reptile house at London Zoo had been turned into a very lucrative
cockroach breeding centre.

'There was no support from the Duke of Devonshire, President of the Council,' Cansdale said ruefully,
years later. 'They didn't want a fuss.' And the Council took a time- honoured easy way out, by abolishing

the post of Superintendent in 1953. Greatly to his credit, Cansdale was not bitter about his shabby
treatment. But he was distressed that dishonesty had won the day and saddened that one of the world's
most prestigious zoos appeared doomed to remain inefficiently managed.

It was during his years as Superintendent that Cansdale began to broadcast, for television, from the
BBC's Alexandra Palace studios and later Lime Grove: he was a household name in the Fifties long
before his Blue Peter appearances. His series of animal programmes included Popular Animal Fallacies,
Heads, Tails and Feet, Looking at Animals and All About Animals. These last two series won him the
Royal Television Society's Silver Medal in 1952. There were outside broadcasts from the zoo itself
(Wynford Vaughan Thomas was bitten by a large Indian gecko, during a relay from the reptile house.) For
radio too, Cansdale was a regular contributor to Children's Hour.

In the 1990s, with its plethora of wildlife programmes offered by all channels, this may seem
unremarkable, but they all owe a debt to George Cansdale. He was a pioneer of scientific broadcasting
and a tribute to his work in this field was paid by Sir David Attenborough in 1992, in his presidential
address at the AGM of the British Association. 'A lot of thinking people, in those early days, took a fairly
lofty view of television, regarding it as so populist as to be beneath their notice.' But natural history
programmes started off with a thoroughly scientific base and Attenborough said it was thanks to
Cansdale's bringing animals to the studios from London Zoo 'that a great many people, young and old,
acquired their first insights into taxonomy and comparative anatomy from what he said. He spoke good
natural science.'

In addition to broadcasting, Cansdale lectured and wrote many books. Early titles included Animals of
West Africa (1946), Animals and Man (1952), George Cansdale's Zoo Book (1953), Belinda the Bushbaby
(written with Sheila, 1953), Reptiles of West Africa (1955) and Behind the Scenes at a Zoo (1965). West
African Snakes published in 1961, remains the standard work on the subject and was reprinted in 1992.
Animals of Bible Lands (1965) entailed a study of every animal name in the Bible's Hebrew and Greek
texts from the 'moving creature' of Genesis I to the figurative 'dogs' of Revelation 22. Cansdale
described it as 'a fascinating task', but he was the first writer for over a century to attempt such a
colossal project. His wife was an invaluable ally in this enterprise and in 1960 they spent a month
wandering through the Lebanon, Syria, Jordan and Israel and toured Israel again in 1962.

Cansdale's energy and versatility were legendary. In the 1960s he became Director of Morecambe's
Marine Land, Chessington Zoo and Natureland in Skegness. It was whilst he was with Natureland that he
pioneered a way of obtaining clean seawater by drawing it through the sand in the beach. Realising this
idea could be adapted to provide clean water in developing countries, he set up SWF Filtration Ltd with
his younger son, Richard, to make the necessary filters. The company won a World Business Award (the
IBM Award for Sustainable Development) in 1990.

Throughout his career as a scientist, broadcaster, writer, lecturer and inventor Cansdale always
empathised with and had time for children. His cottage in Essex became a magnet for the village
children as well as his much-loved grandchildren. The treat was accompanying Cansdale to the Blue
Peter studio - one or sometimes two at a time, so there was a lengthy waiting list and Cansdale
administered a rota with typical impartiality. Nine was the magic age when he allowed his young friends
to join him and assorted wildlife and a boot-full of garden produce on the journey to Television Centre.
'Mr Cansdale, I'm nine next month - can I go with you, please' was the constant cry.

Cansdale would always telephone in advance, and invariably the message would be the same. 'I'll come
to the office first, I've a basket of windfalls - a load of beetroot and flowers. Oh yes, and there's some
chutney and marmalade for you.' And a cornucopia of goodies would appear - enough for every member
of the production team. There was never a more generous or warm-hearted contributor or one who
produced more delicious jams and chutneys.

There was no so-called 'retirement' - even when an unlucky fall in 1991 resulted in a badly fractured
femur, hospitalisation and a long and painful convalescence. His letter to the Telegraph in June of that
year contributed to the debate on the current London Zoo controversy. He bitterly disagreed with the
Grade I listings of the Penguin Pool and the Gorilla House - pointing out they were not designed with
animals in mind. He also criticised the Snowdon Aviary and the Elephant House - in his eyes neither of
them merited retention.

Cansdale triumphed over many vicissitudes, including the loss of part of his foot in the early Eighties as
a result of skin cancer from his years in the tropics. But the cruellest blow of his whole life was the
death, in March last year, of his beloved Sheila. Never in robust health, she had suffered from various
illnesses for many years. But for the last two years of her life she was nursed devotedly by George.

He continued to live life to the full - despite problems with his broken femur that put a stop to his
driving. Neighbours and his sons David and Richard and their wives, to whom George was devoted,
rallied round but he was resolutely independent - accepting help with the garden but continuing with his
chutney-making and his support for Inter-Care, a charity collecting medical items for African Mission
hospitals. He regularly accumulated monthly parcels worth pounds 200 - typically thinking of others,
rather than himself, to the very end.

Good morning,
I am very frustrated. I completed this morning's story, but when I hit the 'Post' button, it didn't respond
for a few moments, but then when I thought it had, the text disappeared and hasn't been seen again.
So I will just smile and start all over again....
Preamble.
WALKS can take a number of different forms. Some are exploratory; you don't quite know where they
will lead, but for others you can have a guide who will point things and tell you stories along the way.
I have just realised my ramblings are both, simultaneously. For me they are the former. I am delving into
my memories and seeing where they lead; but you are joining me and I will share stories along the way.
So hopefully this will be a win win situation for us all.
Today I wanted to explore my father's very first involvement with television. Before writing I had to do a
little research to check my facts, but I am now quite confident that I have pieced the bits of the jigsaw
together.
1948 was the year my father left his job as a forestry officer in the Gold Coast (which from now on I will
refer to Ghana) and took up the post of Superintendent of London Zoo.

BBC had starting television broadcasting in 1936, then after a gap during the years of the Second World
War, resumed again in 1946. In 1948, soon after joining the zoo George contributed to 'Picture Post', a
programmed the BBC describe as the word's first Magazine Programme. He showed a squirrel.
I can only guess at this, but I suspect the squirrel would have been one from his animal collection in
Ghana. If he had handled it since it was very young he could sure it would be well behaved. and because
he knew his subject well, and was so enthusiastic, he would have been relaxed and confident and come
across well. That is how within a very short time he came to be presenting his own animals for children,
namely 'Looking at Animals' and 'All about Animals'. In 1952 the Television Society honoured his work
by awarding him their medal for the best programmes of that year.
Then for a few years he did little television work, but when Blue Peter started he was the natural choice
for its regular guest presenter for animal topics. He contributed numerous times to Blue Peter right up to
the 1980's.
For someone else's perspective do read the obituary Biddy Baxter, the former iconic Blue Peter editor,
wrote for The Independent when George died in 1984 aged 83.

* * *

I will now post this, and also post the text of Biddy Baxter's Obituary for your interest. Or I will TRY to!
or, here is a link to it....
https://www.independent.co.uk/…/obituary-george-cansdale-14…

WAS I THE VERY FIRST THEME PARK VISITOR EVER?
In the messages which followed my last posting I was asked about what I think of as the Blue Peter
elephant's water skiing incident. The baby elephant,Lulu, came from Chessington Zoo where father was
a Director. I think he facilitated the elephant's day trip to London, but he was not in the studio for the
water works.
When he had a Directors' meeting at Chessington my brother David and I often accompanied him. (If you
are reading this now David - don't worry I'm not going to tell the Cockatoo story, or at least not today!)
No, on this particular day, when I was about ten, I was alone. In addition to the animals there were other
attractions. I remember the Hall of Mirrors, the Ghost Train, the Helter Skelter to name a few. To go into
these attractions you had to pay sixpence or a shilling but Harry Snazle, the Managing Director wrote a
note and told me to show to the ticket collectors. Instead of paying for every ride, I had a brilliant time
going as often as I wanted on all of them. I can still remember telling Mr. Snazle what fun I had had.
Had he decided to set a fixed price for visitors to allow them to go on all the rides as often as they
wanted, he would have been 30 years ahead of the game. So, no, I don't think I can seriously claim to be
the first Theme Park visitor.
I have just Google 'History of Chessington Zoo' and found this statement. "In 1987 the new park
development adopted a pay-once price structure as opposed to the fairground's former pay-per-ride
format." This was when the zoo became Chessington world of Adventures.

Walks of Life.

I had never given much thought to the expression "Different Walks of Life" before. Even during our
nation's confinement due to the Corona virus pandemic we are being urged to exercise for he sake of
our health. What are we allowed to do? Cycle, run or walk I think.
Some people stride out to get the heart pumping. What do they call it? Power walking. I prefer to stroll,
binoculars around my neck just watching, thinking and exploring. I am so lucky to be living in Hartburn,
because there is so much to see. Yesterday my friendly fox was there again. I watched him moving
around and then curl up tightly against the chill wind.
I see the dippers every day. I knew they nested in the rocks but it was because I have had the time to
watch them this spring, I have now spotted exactly where the nest is.
Yesterday I likened my writing to an exploratory walk for me, but a guided walk for you, then late last
night, just before coming to bed I was delighted to discover, quite by chance, where the tame tiger my
father used to stroke came from. (In my very first post I talked about the day my brother David and I
climbed over the safety barrier and got much too close the tiger, and as a result got into big trouble.)
I can tell you how I this came about. I went up into my study to look out some pictures to add to today's
post. Biddy Baxter, in George's obituary referred to his controversial departure from the zoo so I thought
I would include an amusing cartoon which touched on this. The caption reads "Is that the Zoo? This is
Viscount Chaplin's residence." (Please don't ask me to explain. Without some further research I really
don't know what the significance is at present.) While looking out the original art work for the cartoon, I
found a picture of George with the tiger in question, and then with it a collection of animal stories for
children. One of these is the story of Baccha the tiger cub. I suddenly remembered the tiger was not
Rajah, it was BACCHA, (Pronounced Barcher.)
The story explains how Baccha was found as an orphaned cub by a patrol of British Soldiers in the
jungle in Malaya. It was emaciated and starving, taken back to show their colonel, and rescued from
certain death. It was raised as a pet, but then sent back to London Zoo. By now it was getting quite
large, but it was not thriving. It was getting thinner. It was then realised he was depressed and missed
human company, but when this was rectified he recovered and did well. He then lived in the Lion House
at the Zoo, but it recognised my father in crowd, who would regularly stroke him through the bars.
So, perversely, as a direct result of this dreadful pandemic, I have embarked on a voyage of discovery
which I may never have got round to had it not been for my involuntary self-isolation. It would be lovely
to think you are enjoying reading my stories as much as I am writing them. Goodness only knows what I
will discover.
Or, as someone often accused of having an obsession with my stove can say "It's an ill wind that blows
nobody any WOOD."

Good morning all,
If I was to say "Good evening all!" I wonder how many of you would know whose catch phrase that was?
Dixon of Dock Green was a TV police series, introduced by a character George Dixon, played by the
actor Jack Warner. It was first screened in 1955 and ran for 432 episodes until 1976 amazingly.
I have only just realised this, but a few of you have mentioned my preambles before I start my story of
the day. That was just how the Dixon of Dock Green stories were introduced.
This morning I will touch on hate mail, and how George responded to it. A curious topic you might think
- but nothing new.
Two evenings ago when I looked out the Tiger pictures I also found the cartoons I have included today. I
particularly like the bear one. You will see there is no mention of George's name. There was no need
because by now he was such a well known face.

It is hard to credit it, but there was only one television channel at that time, and it only broadcast for a
few hours a day, so no choice whatsoever. I suppose it was a bit like the Monty Python SPAM sketch.
What if you don't like spam?
We all tend to warm to some people and not to others. It is a natural human instinct, but then the
extreme version of this is the vile habit of on-line abuse. As I said, this phenomenon is not new but in
father's day people would write nasty anonymous letters.
Father's response was to file them under the "FUNNY LETTERS" and with much amusement quote them
when the occasion arose. One of his favourites I can quote almost verbatim. (I have toned it down
slightly so as not to cause offence.) It said this......
"Mr. Cansdale, Every time I see your **** features on television it makes me want to throw up. I was so
sorry that the fruit bat bit your finger. I wish it had been your throat!"
There must be any number of reasons why people write letters like, and I know it is really horrible to be
on the receiving end of them, but father's way of coping with them was classic.
Have you wondered why I should have given my ramblings the working titled of "Third cage on the left?"
I will soon be telling you how having just turned eight, I was sent to a boarding Prep school in Sussex.
Sounds inhumane doesn't it, and I was teased for having grown up in a zoo, but as I have already said, I
put it down to jealousy and laughed it off.
But for all the nasty letters there were countless positive ones. I think he replied to each and every one.
When we moved from London Zoo, it was only a few miles to Lyndale Avenue in NW2. Number 45 is a six
bedroom semi-, which allowed father to have a live-in secretary and my mother to have an au pair girl to
help her. With David and me too, it was quite a busy household.
So what was my father to do now? He had lost his salaried post at the zoo, so his departure offered new
opportunities. I don't think he was ever worried about any shortage of work because he now embarked
on writing, lecturing and public speaking, zoo work and still some television appearances. He also had
time for hobbies, charity work, and for 25 years he was a Church Warden at All Souls Langham Place. If
all that doesn't make you feel exhausted, it does me!
I will stop now and have some breakfast.
Just one more think. If you are able to read the letter below, look at the small print a the top of the page!
One word sticks out as such a strange choice of language. See if you can spot it. I don't know if there
will be sufficient definition, but it amused me.
Hang on in there every one. Grim times. Do those things you aways promised yourself you would do.
That's why I am boring you with my ramblings.
Have a nice day. x

Preamble.
Yesterday were were told 562 people had died from the Covid-19 virus in the previous 24 hours. We are
living in such a dreadful worrying time and are all having to draw on all of our resources as individuals,
as families and as a nation.
I am sure there are countless others like me, who are over 70 and have been told to self-isolate, who are
being supported by friends and family who are shopping for us; phoning us regularly to check we are
ok, as well as trying to work if they can and looking after their own family. Thank you each and every
one. That is on top of our massive debt of gratitude to the self-sacrificing work being done by our
wonderful NHS staff.
I started writing my personal story two and a half weeks ago after sharing coffee with my friend Pam
who went down with the virus the following day. I am pleased to say she is recovering, but has had a
very nasty time. I am keeping very well, so probably did not get the virus, but who knows? We are told

many have no symptoms whatsoever. I did have a very slight tight chest for a few days which I can no
longer feel. Was that the virus?
Some of you are dipping into these ramblings over your morning coffees today, April 2nd 2020, perhaps
some are reading these words years after the Coronavirus Pandemic of 20202 has slipped into history.
At this present time we have no idea what the future will hold for us or how long the pandemic will last.
Just a few short weeks ago we were worried sick about global warming and what we humans have done
to our beautiful planet by greed and over consumption. Today the airlines are all but grounded. The
larges cities are in lock-down and our roads are silent. We are having a massive wake up call. Is this our
planet revenge?

* * *

Today my story will see the family leaving London Zoo and moving to NW2. Just before we do I am
attaching a photograph of some people walking through a tunnel.
Can you guess where this is?
A few years ago I was watching a documentary on London Zoo when I saw a clip of the tunnel in which I
had my tricycle accident in 1952. I froze the picture and took a snap of it. My crash was on the left just at
the start of the rounded arch.
I found the photo while looking for some pictures to accompany today's post but to save time now I will
post the preamble and then post the main story hot off the press later.
Keep strong and stay safe.

## Pets at Home

In 1953 our move from the Zoo to NW2 was only a few miles. Walking distance from Hampstead heath,
but on a route which offered equally good access to the West End and to open countryside.
This six bedroom semi- accommodated the family, my father's live-in secretary, my mother's European
au pair girl but in the custom built, insulated shed in the garden, my father's collection of pets. Some
common, some exotic.
In the house was our much loved tabby cat, Popa, named after the Mexican volcano, Popocataptl, and
the Liisa, the Finnish Spitz. A lovely dog, but its other name of the Finnish Barking Dog should have
warned us that it was perhaps not the best choice when surrounded by neighbours. In Finland they run
ahead of hunters and bark at base of trees into which game birds have sought sanctuary.
In the dining room was my budgie and a re-homed African Grey Parrot. In the drawing room my brother
had tropical fish, and in the garden itself one or two tortoises, The Blue Peter tortoises lived with us;
First there was 'Fred' He became 'Freda' when he, sorry she, laid an egg. For a while the second Blue
Peter, George also lived with us. After the fishing expedition to the Woburn Chinese Garden pond, the
two anonymous gold fish joined the family.
It was in the garden shed where things started to get more interesting. The cages always contained a
range of common pets, Netherland Dwarf rabbits, Guinea pigs and White and Hooded Rats.
There were always at least two snakes. A Royal Python, also known as the Ball Python, with its most
beautiful markings, and an African Python, which tended to grow and grow and grow. These were joined
by a Boa Constrictor. All of the snakes were handled regularly and taken by my father when he spoke to
schools, clubs or Women's Institutes etc.
The star of the show was Polly, my father's Bush Baby. My father had Polly for many years and she made
countless appearances at father's lectures. If the audience was large he would take Polly to the back of

the hall and put her on someone's shoulder. He then walked to the front of the hall, where Polly would
rejoin him having jumped from shoulder to shoulder the entire length of the hall.
Those were the residents. We then entertained 'animals in transit'. B&B you could say - in boxes or
behind bars! You never quite knew who would turn up, or how they would arrive. It seemed that anyone
with an animal they no longer wanted would ask George to re-home them.
On day a couple turned up with a monkey. The wife was in tears as she got into the car to leave, but
before her husband left he whispered into my father's ear, "I'm so glad to be shot of that wretched
creature. She would bring it to bed with her!"
I have just remembered how one of the tortoises arrived. It just had a piece of newspaper taped around
its shell with the head and tail poking out at either end. I cannot recall who delivered it, but I think it was
the postman himself. Full marks for imagination to the sender. It was better than dumping it as some
irresponsible exotic pet owners do today.
Although it was my father's secretary who helped look after the animals in term time, when David and I
were at home we helped too. Father was a keen gardener so all the soiled bedding went on the compost
heap. Horse drawn carts were still used by the rag and bone men, the recycling operatives of the day,
and from time to time they would come round offering a load of manure for gardens. We delighted in
saying 'We make our own!" which never failed to raise their eyebrows.
One weekend we looked after a lion cub in transit to another zoo. Then for a few days a delightful black
bear cub was staying. He was very tame and could be walked on a lead. The current au pair girl was
animal mad and took it for a walk to the shops on Finchley Road. She returned home in tears.
Apparently nobody had shown any interest in young bear even when she started stopping people and
telling them what she had. I still think it was so strange.
One day a new au pair girl had just arrived. It was a warm summer day and we were having a cup of tea
in the garden. Suddenly she too burst into tears! A tortoise was approaching her chair.
To my mother's horror she realised she had forgotten to mention we had animals, and this poor girl
appeared to have an animal phobia. The offending tortoise was removed to a safe distance and since by
good fortune we didn't have any animals in house itself at that particular time there was a possibility
things might still work out, provided no mention was made of some of the residents in the Animal
House.
In the event, an animal-free family was located and the lass would go to them after a couple of weeks.
During this time she actually got used to the tortoise and was not bothered by the fact that there were
animals in the garden shed. She didn't need to go in there. It was shortly before leaving that she
discovered the awful truth. "You never told me you had SNACKS!" were her immortal words.
It was sad that a few days later she did move on because by then she was already less worried by the
snakes in the shed and given a little more time she may well have stayed. On a number of occasions
father cured people of their irrational fear of snakes, but you can't win them all.

* * *

So let's take a break.
A few picts to make you smile.

Good morning dear friends,
PETS LEAVING HOME.
I cannot believe that things will ever be the same after the Pandemic. Even when we pass the peak of
infections we won't know for a long time how long it will be beforesome form of normality return.

Until recently on clear mornings I would often see half a dozen vapour trails criss-crossing the sky. For
the last couple of weeks I have not seen one, but a few minutes ago I looked up to see a single
east-bound one from the bathroom window.
So much has changed in world since we were born, and even more during our parents lifetimes. Travel,
communication, health and photography to name just a few. Will we change how we expect to be able to
travel so much in future, pumping CO2 into the atmosphere. I wonder.
Zoos too have had to change, and if you are thinking "Good job too" I couldn't agree with you more.
They had too, and they have, thank goodness. I will be exploring this subject at some stage.
I am getting a little ahead of myself, let me tell you about a few incidents I recall from our time in Lyndale
Avenue.
I had been given my first Budgie by Mr. Palmer, proprietor of his big pet shop in Camden Town. He was
blue (the Budgie, not Mr. Palmer), and I called him Winky. In time Winky died and was replaced by a Grey
green budgie, Smokey. One day I was in front of the house only to see Smokey sitting on the fence like a
mugwump. (I'll explain in moment if you've not heard of a mugwump.)
I didn't want him to fly off so I approached him slowly, offered up my finger, and as he alighted I
deployed my thumb to hold him down - and I had him. I took him into the house, only to find Smokey
was still in his cage! It wasn't Smokey at all. I now had two. I think we must have put a sign on the gate
telling people that we had found him because we didn't keep him long. No social media in those days.
Unlike today, house sparrows were very common in our gardens. Their cheeky chirping call was imitated
by the budgies who I suppose had Cockney accents. The sparrow caused havoc in my dad's vegetable
garden, so he gave me an air rifle. Did a lot of target practice but the best way to scare off the spuggies
for me to place old tin cans and buckets in the garden and then fire at these targets.
On hot days the Animal house doors and windows were left wide open, and one day the Royal Python
was missing. Strangely its tank lid was still secure, but we searched high and low to no avail. All the
pythons were called Percy, plus an adjective. This was handsome Percy.
A few months later I went into the Animal House. The doors and windows were closed, and there, curled
up on top of the snakes' tank was Percy. He was in good condition and must have been returned by the
thief. A mystery we never solved, but I wonder if someone in the thief's family discovered where he had
come from and demanded the perpetrator took it back. Years later I had another stolen item returned in
the strangest of circumstances. That can wait for another day.
Almost forgot. Mugwumps? “The first political mugwumps were Republicans in the presidential race of
1884 who chose to support Democratic candidate Grover Cleveland rather than their own party’s
nominee. Their independence prompted one 1930s humorist to define mugwump as ‘a bird who sits with
its mug on one side of the fence and its wump on the other’.”
David had his tank of tropical fish in the drawing room and from time to time we went to the pet shop in
Hendon to get some new ones. To collect them, and keep the water warm for the journey home we filled
one of our mother's shopping bags with large glass Kilner jars, plus a hot water bottle for warmth.
The bag was quite heavy so we had a handle each.
The bus stop on the Hendon Way, a dual carriageway, was about one hundred yards short of a busy
intersection with Cricklewood Lane. As we waited to cross the dual carriageway we saw the bus coming
down from Finchley road, but we didn't get to the bus stop in time. Luck was on our side because the
lights turned red and the bus was forced to stop at the cross roads.
Not wanting to wait for next bus we sprinted for it. David was faster than me and leapt on board just as
the lights turned green. He held onto the pole with one hand and the bag handle with the other but the
bus was now travelling at a considerable speed. David pulled his handle as I pulled mine, and by a
miracle I took a final leap onto the bus' platform. Exhausted and out of breath I collapsed onto down a
back seat.
