# Life in the Zoo

Our house in the zoo, long since demolished, was between Regents Park’s Outer Circle and the Regent’s
Canal. From my bedroom window I looked down on the canal, which was still in commercial use, and
can clearly remember horse drawn barges. Beyond the canal was Primrose Hill and to the left a white
block of flats which are still there in Ormonde Terrace. - you can see them by using Street View on
Google Maps! I mention this because I named the flats The Teddies’ Gonking School. Now why might a
small child come up with that name? For a long time I could think of no logical answer, but then I
realised that when lying in bed I could often hear a dull thumping sound. It was my heart beating, but my
explanation was more imaginative. I could hear the teddies Gonking.

Lying in bed, in addition to the continuous gonking of the Teds, I could hear other sounds. The
Kookaburras were within earshot, and their call was the first bird sound I knew. Also known as the
Laughing Jackass, not a bad name for some people I know today, their distinctive cackle was loud and
clear. I could also hear the lions roaring at night. They didn’t worry me as much as the leopard I was
convinced lived under my bed. I had to turn out the light and leap onto the bed to stop it getting me.

I must have known the grounds better than most visitors, and on at least one occasion I was ‘found’ by a
well meaning member of the public who took me to the lost property office. I must have played along
with this, but that got me into trouble with father and I don’t think I did it again knowingly.

My favourite animals were Dixie, the female African Elephant, Prince, a beautiful Cheetah, and Rajah a
very tame tiger, who father would stroke through the bars. This did cause serious trouble when day
David and I climbed over the safety rail to get closer to Rajah. Too close! I don’t think we touched him,
but we had been seen by the head keeper. Later that day we were heading off for a family picnic, when
as luck would have it just as we were driving past the offices as the wretched man was crossing the
road. He flagged my father down and snitched on us. Perhaps he also saved our lives, but there was no
picnic that day.

Rats were a menace and a sixpence bounty was paid for any caught. Father had a shotgun and some
evenings we accompanied him on his rounds. He would shoot rats in the moats in front of the Mappin
Terraces. I had a swing in the garden and one day I washed it with a rag and a bucket of water. I didn’t
put the bucket away, but in the night a rat climbed into the bucket and drowned. Poor rat, but I was rich
with my sixpence.

World War II had only finished three years before we moved to the zoo. Rationing was still in force and
times were hard, so people had to make do as best they could. Unfortunately not everyone was honest,
and among the zoo staff there were opportunists who used their situations to their advantage.

As the public paid to come into the Zoo they moved through turnstiles which recorded the numbers
entering. It was cash only and this temptation was too much for some. At some point father realised that
the numbers coming into the zoo did not tally with the takings at the gates so he decided to investigate.
He soon learned that the turnstiles were far from foolproof, and offered several ways to be tricked. I
think he said in addition to one or two obvious techniques there were another half a dozen more subtle
ways to cheat. It was when father saw the man in charge of the gates coming to work by taxi, a luxury
out of the reach of his salary, that he had to act. Father would of course have known exactly how much
he was earning so he had the turnstiles removed and replaced by new Automaticket machines. (You
could buy a vintage one today on eBay for £200.)

There were other ‘rackets’, as father called them, rife in the zoo. A lot of food intended for the animals
ended up on dinner plates, but one ingenious scheme only came to light when he inspected the reptile
house late on night. As he went in he saw what he described as rafts of cockroaches on the floor.
Thousands of them! When he demanded action be taken to, suggesting poison, the objections by the
keepers was extreme. It turned out the cockroaches were being bred intentionally and sold to schools
and colleges for dissection in the biology lessons.

Stamping out these practices did not go down well with staff. They did not forget what he had done, so
when father’s post was abolished a few years later, despite a massive public outcry, they had their
revenge. More of this story in another chapter.
