# The Gold Coast Years

My first two posts were my childhood memories until I was six, but at this point I will answer a question
often asked "How did your father come to be given the post of running London Zoo."

The explanation I will give you could fill a book of its own. It is fascinating, but here is the short version.

My parents, George and Sheila met at Oxford University in the very early 1930's but they were from
entirely different backgrounds. My father's father was a clerk for a shipping company in the London
docks, my mother's grandfather had founded a large department store in Southsea, Handley's. At its
peak the store employed 500 staff, and something I found out only recently, when there as a local
airshow a company making kit planes approached Handley's offering them an agency for their planes.
My great grandfather must have a sense of humour, because in flyer (excuse the pun) for the store's
general products it included these words. "Also Airplanes, care of the Plumbing Department".

So, going back to my parents, they had met at University. My father studied Forestry, my mother History.
My father graduated in 1932 but it was during depths of the depression. (Sounds familiar?) Most of the
forestry graduates would have expected to get jobs with the Colonial Service in either Africa, or Asia,
but in 1932 there were NO jobs on offer. None. Father did a one year research degree studying the
Classification of the Black Poplars, really exciting stuff, but it gained him an FLS (Fellow of the Linnean
Sociiety). The following year there were four posts advertised by the Colonial Service for forestry, but by
then there were graduates from two years from four universities after them. In addition to Oxford,
Edingburgh, London and Bangor offered degrees in forestry.

Father had spent at least one summer in Germany and had learned German, and he believes it was this
which clinched the job for him.

So in 1934 a 25 year old George Cansdale headed off for West Africa, destination the Gold Coast, now
Ghana.

For a young man whose interest was natural history, to be spending his working life in the tropical rain
forest was heaven. Unlike East Africa, with its large game parks, the West African wildlife was much less
known, so father was in his element studying and collecting animals. His particular interests became
small mammals and reptiles.

For years his day job was conducting surveys of the forest, identifying the types, quantities and maturity
of the different commercial tree species, This involved trecking out into the forest for about three weeks
at a time, but this gave him an excellent opportunity to collect animals. Soon after arriving he had got to
grips with the local language 'Twi'. (The T pronounced 'ch', so "Chwee".) He remained fluent for the rest
of his life and on several occasion in London when he spotted someone who he could tell was Ghanaian
he would ask they where they came from. If, as he correctly suspected, they where native Twi speakers,
he would reduce them to either hysterics or tears when the started speaking together in Twi. Once he
was on a bus sitting behind two ladies speaking Twi. As he got up to leave he leant forwards and said
quietly "Be careful what you say, you never know who might be listening."

I must tell you about a funny incident I once had. A few years ago I was in London with Sue attending a
Transplant conference at Church House in Westminster. Afterwards we took the opportunity to visit the
House of Parliament. It was mid December.

I guessed that the lift attendant was West African. He confirmed that he was indeed. Ghanaian. I only
know two or three Twi expressions, 'Mi num' which means 'i drink', and 'Mi num' which means 'I don't
drink'. Hold on, aren't they the same words? Exactly! It is a tonal language, so the slightest difference in
tone is needed to distinguish them.

My third expression is 'Afrishiapa madam foo' which as it happens means 'Happy Christmat my friend.'
The lovely lift attendant was gob smacked when I wished him Happy Christmas in his own language, but
disappointed that was virtually all the Twi I knew, but then was amused when I told him I was 'made in
Ghana'. "So you are an African!" he told me.

I'm afraid this chapter is going to be quite long, especially if i am going to digress, so i am taking a break
now.

George threw himself into his forestry work and soon learned the local language, Twi He would proudly
tell me that he was the first European to learn it to translator standard. This greatly assisted his ability to
learn about the wildlife in the forests from the local people.

Over next few years built up a collection of live animals, recorded as many mammals and reptiles as he
could and even discovered half a dozen new species or sub species as yet not known to science. These
included Mrs. Cansdale's Bat, and the unromantic sounding Cansdale's Swamp Rat.

Some 40 years after leaving Ghana George was speaking to a Rotary club in York when after the talk a
Rotarian came up to him and said 'Mr. Cansdale, when I worked in Ghana I lived in the house you had
lived in.' When father asked how he knew that he was surprised by the answer.

'When I was allocated the house several people told me how lucky I was to have it. I asked why and was
told 'Many years ago a man lived in that house who had power over the snakes. His spirit is still there so
thieves will not go there. " '

He had taken up his post in 1934, and every two years was able to come home on leave. My parents had
met at Oxford University but did not get married until September 1940. They were married in All Souls,
Langham Place on Saturday the 7th September. I mention this for two reasons. First, you have often
seen pictures of this church, possibly without knowing its name. It is the church alongside BBC
Broadcasting House with the ring of columns, and tall conical spire. It is often shown before or during
news programmes. It was designed by the architect Nash, along with many of the building in Regents
Park. The church was to play a big part in my parents' lives for many years.

The second reason I mention the date of the wedding was that 7th September 1940 was the first day of
the daylight blitz. As my parents traveled to Devon on the train for their honeymoon they remarked on
the sunset, until they realised they were looking EAST ...... at London burning!

After the wedding my father returned alone to Africa. He was never in the armed services other than the
equivalent of the Home Guard. His knowledge of German meant that he had to check the letters of
German Internees for compromising information. The only thing of interest he found was a blank note
book along with covering letter saying that in view of the shortage of paper at home, here is something
for you. His suspicions were aroused and he discovered the pages had been written with invisible ink,
giving details of shipping in Takoradi harbour.

He was in charge of one two platoons. During on exercise his platoon was to attack Government House,
the other platoon had to defend it. Did he commandeer an Ambulance, Dirty Dozen style? No, he used
the dust cart. Having washed it out first, he piled his platoon into the back and drove in through the
gates unchallenged.

During the war father's role was supervising workshops making furniture for the forces. Tables and
chairs and beds. He had a reputation for spotting disguised defects so he carried with him a hammer
with which he could reveal shoddy repairs with a well aimed tap. As he approached the cry would go up
"The lion is coming.The lion is coming." At the end of the war he was presented with a magnificent
traditional wooden stool fashioned as a lion.

My mother visited my father for two tours, first in 1943/4, and then in 1945/6.

Visiting Africa for the first time can be quite a culture shock, but one of the things my mother was not
expecting was to hear my father speaking Pidgin English to his staff.

"I don't mind you speaking in this funny way to your staff, but I hope you won't expect me to" she said to
him. My father told her not to worry, but a few days late his steward approached him looking very
concerned.

"What's the problem?" he asked, The reply was classic, especially considering my mother's education
and upbringing.

"Massa, dis missus, why she no speak proper? I no fit hear-um!"

The end of the war.

My paternal grandmother, was from a Paignton family in Devon and father had links with the Zoo. Along
with most European Zoos their animal collections had suffered during the war years so father arranged
a shipment of animals to Paignton Zoo. He also had contacts with London Zoo and I understand he also
sent a significant number of animals to them too. I don't know how many consignment he send to
London, but they included monkeys, snakes and other animals of interest, but clearly he impressed
them with both his knowledge of the animals he sent and the efficiency with which he sent them, so
when they were looking for someone to take up the post of Superintendent, responsible for the running
of the Zoo itself, they offered him the job.

He therefore resigned from the Colonial Service and in 1948 started his new job, and new career at
London Zoo. I was just one year old.

Before I pick up, a short comment on our present crisis.

Good morning dear friends. I wonder how many of you keep diaries? I would not consider myself to be
particularly disciplined, but from the time I was about ten years old I started keeping diaries. To start
with they were just single years, and the entries were pretty basic, but over the years I started to write up
a bit more.

I now keep FIVE YEAR diaries. I started a new one this year, but the first year is a bit dull. By the fifth
year you can look back over the previous four years and be reminded of events you might otherwise
have forgotten all about. It is a silly habit, but quite fun. The period we are now experiencing is the most
challenging most of us will ever have experienced.

As most of you will know Sue and I lost our most wonderful daughter Zoe in 1998 when she was 22. This
year will be 22 years since she died. And for me it is now two years since Sue died. We often said Zoe
would never have wished her loss to have destroyed our lives; likewise I know Sue felt the same.

I am so thankful that Sue did not have the additional worry of a pandemic for last few months of her life.
She had so many friends visit her during her last few weeks, and the last she did before she fell asleep
for the last time was to give an old school friend a massive smile.

I say this because we must be strong. We will all be tested, but for any of us who keep diaries, (and why
not start one today if you don't already?) when next year we read what we have written today, we will
think back and think "was it really like that?"

WELL ENOUGH RAMBLINGS, this leads me on nicely to conclude my father's time in Africa.

A few years ago I found my mother's five year diary covering the years 1942 to 1947. I didn't know she
had one, although it is about somewhere I can't put my finger on it right now, but one thing interested
me. Where were my parents nine months before I was born? So I looked up 13th June 1946.

It was clear they were in the Gold Coast, so I WAS made in Ghana, but better still, this is what she wrote.
"KING'S BIRTHDAY. HOLIDAY!"

My father not only enjoyed his time in Africa but he made such full use of it it puts me to shame. Long
before colour photography he took black and white photos of his animals and the life of the people. He
processed most of the photos himself and would tell me how difficult this was because of the constant
high humidity. Some of his pictures are archived with the Geographical Society's collections.

The Governor at the time, Sir Alan Burns, was also very interested in wildlife and they became friends.
This friendship, between a lowly forestry officer and the senior civil servant, and the head of the Colonial
Service in the country was resented by my father's bosses, and sometimes ruffled feathers, and might
have been the reason he liked the expression "Those that matter don't mind. Those that mind don't
matter."

In the following years I would learn how much he was respected by his African colleagues just as I know
how much he respected them. It was strange for me, because although I was 22 before I went to Africa
for the first time, and then had a total of 44 trips between 1969 and 2010, it almost felt like going home.
My father's experiences had rubbed off on me as a child and stood me in good stead when I started
working in African water development years later.

In the previous chapter I mentioned how my father sent many animals back to England after the war.
Thanks to a very timely reminder from my cousin Michael Cansdale, who was very close to my father
and went to the same college as him, I can tell you how he was able to do that.

This is Michael writing.........

"My uncle George Cansdale, was at St Edmund Hall, Oxford, from 1929 to 1934. In 1934 he joined the
Colonial Service and was immediately sent out, at the age of 24, to be a Forestry Officer in the Gold
Coast (now Ghana). He stayed there throughout the war when his role was to send timber back to Britain
and to the colonies for the war effort.

But, what was he to do with the extensive collection that he was building up? He got in touch with his
old University friend, Francis Finch, who was overseas freight manager for Imperial Airways and then
later BOAC. Whenever a plane landed at Accra with spare cargo space, Finch would arrange, pro bono,
that animals and reptiles (snakes in particular, and small animals like bushbabies) could be loaded on
board, and sent back to the London Zoo and other European zoos, whose stock had been depleted
during the war. (If only informal arrangements with airlines could be made so easily nowadays by
friendship with their senior staff!)

The direct result was that when in 1947 the Council of The London Zoological Society needed to appoint
a new Superintendent to run the Zoo, they head-hunted Cansdale, who they knew to be not only a
knowledgable naturalist but also a great supporter of and contributor to their collection.

As a boy I regularly stayed with him at the Superintendent's House in the Zoo grounds in Regent's Park.

Very quickly after his appointment at the Zoo he realised the potential publicity that could be obtained
for the Zoo by using radio and the new medium of television to show interesting animals, live, in the
studio. He became one of the best known presenters of wildlife programmes and items on British TV
between the 1950s and the 1980s, and made regular appearances on Children's Hour, and, for many
years, on Blue Peter. David Attenborough, who joined the BBC as a junior manager in 1952, and quickly
became involved in programmes from the London Zoo, has paid warm tribute to George Cansdale's
pioneering work in that field."
