# Monkton Combe and the Big Freeze

Some of the school rules will sound so ridiculous and petty today that I will tell you about them. Third
and fourth form pupils had to have their jackets buttoned up at all times. That's not all. You had to have
TWO of the three buttons done. If you were caught with an open jacket, woe betide you. Fifth formers
still had to have their jackets buttoned up, but need only have one button. But the sixth formers were
free to show their elevated status by swanning around with their jackets unbuttoned. It still sounds quite
bizarre.
The jacket was grey Harris Tweed, but in the Summer term you could wear a Navy Blue blazer. Now to
reinforce status further, if you got into the top teams you were awarded your 'Colours' consisting of
broad striped ties, or, in the case of the elite rowers, a cream blazer. The First VIII blazer was trimmed
with a continuous navy blue ribbon, the Second VIII with alternating blue and silver squares on the
ribbon.
The following incident occurred during dinner in the large communal dining hall. You have to picture 300
boys, seated nine per table. One boy would go to the serving hatch to collect the meal for the whole
table. This evening the dish was ravioli in tomato sauce. A junior boy is balancing the full dish of ravioli
on top of a wobbly pile of nine china plates. Head down and concentrating on not spilling anything he is
making for his table.
Meanwhile, one of the prefects, resplendent in his newly awarded Second VIII cream blazer is strutting
around more interested in being seen by all and sundry than on watching where he is going. The
inevitable head on collision happens. I will leave the rest to your imagination.
Perhaps it was only a few of the Sub Prefects who were particularly nasty, but for me that was enough to
steer me away from an aspirations in that direction. I decided very early on that I would mind my own
business, not other people's. I would not openly rebel - that was sure to get you big trouble, but if I kept
under the radar, I was sure I could follow my own interests without too much interference from the
powers that be.
By and large this strategy proved to be very successful. I survived those five years. I made some lifetime
friends and by and large I was happy and emerged unscathed at the other end. I (just) managed to get
the 'A' Levels I needed to go to University. I hope I will not be labeled as 'a typical Public Schoolboy', I
certainly don't feel like one.
In an earlier chapter I mentioned my house master, Mr. Baker whose catch phase was "You've got to
learn to live together." As it happened he had had a challenging war time experience having been shot
down over Germany. He spoke German so had managed to evade capture, but the story within the
school was that for a number of years his nerves were still affected by what had happened. Like most of
the masters, he was a genuinely kind and caring person, dedicated and professional.
The Photographs were taken in November 2019 when I took my granddaughter Maya out for the day. She
lives in Bristol so we went to visit my old haunt, the Kennet and Avon Canal, (about a mile from Monkton
Combe) on which I learned to ice skate in 1963.
The structure is the Dundas Aquaduct which carries the canal over the river Avon, and it was on the
river Avon which the rowing took place.
Plenty more to come about life at Monkton.

In today's narrative I will talk about a dramatic and, for some of my teachers, a very unexpected
turnaround in my academic prospects at Monkton.
I think my experience may ring true with those written off as being 'thick' or perhaps in todays politically
correct language, as 'low achievers'.

## Monkton Combe School, 1960 to 1961

I mentioned earlier that upon leaving my Prep School in Sussex I just managed to scrape enough marks
together in the Common Entrance Exam to be accepted by Monkton Combe School, near Bath in
Somerset.
That is the truth and I can tell what happened. Approximately sixty boys arrived at MCS in September
1960. All but nine went into the Fourth Form, and would take their 'O' Level exams after two years. Nine,
myself included, were unceremoniously dumped in the Third Form. We were expected to need an extra
year to catch up. I accepted my place in the natural order or things and I believed I was 'thick'. At Prep
School I had always been one from the bottom of the class. What was new?
At the end of that first term, six of the nine were moved up into the Fourth Form, and just three, myself
included, stayed in the Third Form. In January '61 more boys arrived, and then a few more in the
Summer term. Life in the Third Form wasn't too bad. I detested the Latin and French, but otherwise did
enough to get along. I was not a rebel; just under the radar.
In September '61 we all moved into the Fourth Form, and during that term we started preparing for our
'O' Levels in earnest. These were the equivalent of the GCSEs of today. Our two Science subjects were
Chemistry and Physics, both of which I found interesting. In Physics we disappeared into darkened
rooms and played around with lenses, determining their focal lengths and creating wonderful spectrums
of colour using chunky triangular glass prisms. It was great fun and the Physics Teacher's catch phrase,
was "Units Laddie. What are they? Pink Elephants?" if you failed to write down the correct units, be they
seconds or millimetres, with the numerical answer.
But in Chemistry there was this mysterious thing called VALENCY. Why was was the 2 in 'H2SO4'
(Sulphuric Acid) or the 4 for that matter. Why was Hydrochloric Acid HCl and not H2Cl if water was H2O.
It was all very very mysterious.
I don't know how it happened, but one day the scales simply fell from my eyes and I suddenly
understood the concept of Valency. It became totally clear to me; almost easy. I don't think I had ever
had an experience like this before. Perhaps I wasn't so thick after all.
The year group was split into sets, A, B and C. So it was perfectly possible for someone to be in A set
for French, but in C set for Maths and the sciences. Guess where I was? Yes, C sets, right across the
board.
Towards the end of that term we all set the same exam paper, but when the results were posted on the
notice board, the chemistry staff had put all three sets' results on the same sheet of paper in three
vertical columns. 'A' Set on the left, 'B' Set in the middle and 'C' Set on the right. I have used our noble
Government's Coronavirus update's envelope to show you a very crude graphic of what that sheet
looked like. (As you know I like re-cycling!)
I will explain. Our names were ranked in order, approximately level with the percentage achieved. As
expected, the scatter of results was pretty well in line with expectations, with the 'A' set results at the top
of the rankings, and the 'C' set at the bottom. But hold on, whose result is circled in orange? One of the
'C' Set results is right at the very top, level with the top marks of the brains in the 'A' Set. Yes, that was
me! I think I had the third highest mark in the year.
The following term I was moved up into the 'A' Set for Chemistry and Physics. Other than French, which
I fully expected to fail, I passed all my 'O' Levels. I then did my 'A's and passed all three, Biology,
Chemistry and Physics, and got my place at Queen Elizabeth College in London University.
I am sure a lot of us will be able to relate to this story; if not for ourselves, for our children or
grandchildren. Tell a child often enough they are 'thick', 'stupid' or 'naughty' and they will believe it. It
becomes a self-fulfilling prophesy. Conversely, help them find their true potential, tell they CAN achieve
whatever they hope, and there is every chance they will.
Tomorrow I will tell you about the winter of '63 and my sporting achievements, (or rather the lack of
them), and badger watching, one of few opportunities to get out of bounds legitimately.

* * *

Postscript. Yesterday the UK death toll for the Coronavirus topped 10,000 and is still rising alarmingly.
Most people I speak to now know someone who has it, and many know, or know of, people who have
died from it. We are in awful times, but we are also hearing of the wonderful selfless work of the NHS
staff, of numerous acts of kindness and support for the isolated and the vulnerable. Let's hope as a
society we will become more caring and considerate when we emerge from these dark days.
Keep safe. Keep strong. If you are feeling low phone a friend and see if you can cheer them up. That
alone will cheer you up.
xxx

The winter of 1963 was cold. How cold? This is from Wikipedia.
"The winter of 1962–63, known as the Big Freeze of 1963, was one of the coldest winters on record in the
UK. Temperatures plummeted and lakes and rivers began to freeze over. In the temperature records
extending back to 1659, only the winters of 1683/4 and 1739/40 were colder than 1962–63."
It was cold, in fact the third coldest winter in the last 360 years.
Although life was disrupted massively, education continued unaffected, unlike the sporting activities.
300 plus teenage boys need to let of steam, and since the normal winter games of either rowing or
hockey the main alternatives were running, or a limited form of hockey played within the school
quadrangle.
I never liked running for running's sake and runs were often given as punishments by sub-prefects for
minor transgressions. This never bothered those who ran voluntarily. After they had fulfilled the required
distance they mocked the punishment giver by saying they were going to do that run anyway. Not a
good plan if the prefect had a good memory. Next time they might regret it.
So if you didn't like running and as a Rower, Quad Hockey was not an option, what else could you do to
fulfil the obligatory requirement to take some physical exercise every day? By great good fortune, the
father of one of my pals worked for Oxfam. They had just set up one of the first charity shops and he
came back to school with a pair of ancient ice skates. The kind you strap onto the bottom of a heavy
boot. My army boot, issued by the cadet force was ideal, so having roller-skated a lot at Great Walstead,
I took to ice skating on the frozen Kennet and Avon Canal as a natural, and have enjoyed ice skating
ever since.
The freeze continued for the entire term. On Wednesdays, we went out and about with the cadets,
walking on the frozen snow over the tops of mature hedges. Every night we walked up the hill to our
boarding house. In normal weather we walked up a local curiosity called a Drung. This was a footpath
going directly up the hillside, between two stone walls. When we first arrived back at the beginning of
term the Drung was packed with snow, so we walked up the field beside it, but as the snow between the
walls compacted we were able to come back down the hill by sliding down a narrow Cresta Run type
groove in the snow, one foot behind the other.
There were no serious accident caused by the freeze, but my classroom that year was in the old village
school. Part of the old playground was a steeply sloping path up to the toilets. We had fun by pouring
water onto the slope and sliding down the resulting ice sheet. That was dangerous enough for us who
knew it, but one afternoon a senior boy who was coming to police, sorry 'supervise' our prep
(homework) session, was caught unawares and had a nasty fall. He was not badly injured thankfully.
Not all of the senior boys fell into the mini-Hitler type of sub-prefect, full of their own self-importance
and power mad. Most were very decent and caring. In my time in Hill House there were a few boys senior
to me, all very clever and decent who went on to great things. Dearlove, became Sir Richard Dearlove,
when he was head of MI5. Stilgoe, became Sir Richard Stilgoe, the impresario well known for his musical
talents, first seen on Esther Ranzen's 'That's Life' programme, but the third was Bernard Wiggins. You
might not know that name, but may well have read some of his books. He is now known as Bernard

Cornwell, best selling author of the Sharpe series of novels. For a while he was my 'Dorm Senior' and a
good sport.
Monkton was good for me, and to me. Most of my friends would probably say the same. For me, it
offered a lot of freedom, but for one of my best friends, Richard Cooper, whose family were farming in
the Cotswolds, it was the opposite. He had a horse at home which he sorely missed and although he
never rebelled, he was not particularly happy there. I last saw him in Australia shortly before he died,
much too young.
The big freeze ended and the cricket and rugby pitches in the bottom of the valley flooded. Nothing
unusual there. That is nature, they are flood plains, just don't build houses on them!
Running up the valley was a disused railway line, known a Clank. Shortly before the line was ripped up it
was set for the 1953 comedy film The Titfield Thunderbolt, coincidentally just shown on BBC2 last week.
The cricket pitch, known as 'Longmead' was in the scene when all the players rushed to see the train
steaming by.
The following (summer) term we either played cricket, rowed and just a few played tennis. I rowed, and
whilst not particularly good, I was reasonably competent. We learned the fundamentals in 'The Tank' a
strange, recently completed contraption where the oarsmen sat on seats surrounded by the water. As
you rowed, you stayed still, but the water went round and round. Quite ingenious in fact.
Most of the boats were 'fours' with four oarsmen and the 'cox', a small boy with a loud voice tucked into
the stern steering the boat and shouting out the commands. The river Avon is too narrow for boats to
race side by side, so a clever form of racing is adopted instead. All the boats are spaced out equally
down the line of the river - pointing upstream. I forget the exact gap, but it is several boat lengths. Upon
starting, the aim of the exercise is to catch the boat in front and touch their stern with your bow. At that
point those two boats pull over to the side, so for the next race, normally the following day, the starting
positions are reversed.
The oar hanging up in my hall at home was won by my father rowing for his Oxford College, St. Edmund
Hall. (Teddy Hall) If you 'bumped' every day of race week, you were awarded your oar.
Regrettably my rowing career ended the following summer. I had realised that if I was to get my 'A' Level
I was going to have to work very hard indeed. I was never a natural academic, and Rowing took up too
much time. The teams went off for entire weekends to regattas scattered around the country, and whilst
no doubt great fun, I had seen too many of the successful sporty types come a cropper with their exams
so I decided to opt out and play tennis instead, just for fun and to get enough exercise. After all, you

could play tennis with just one other person, and perhaps, just perhaps, that person might be wearing a
skirt.
I had made the decision to stop in principle, but the actual moment when I stopped was prompted by a
silly petty decision by the senior boy coaching our crew on the day in question. The walk from the
school to riverside boat house took about twenty minutes. We were meant to arrive five minutes before
the official start time of the 'outing' to ensure there was no delay. On the day in question one or two of
us arrived exactly on time, just as our boat was being disembarked by the earlier crew. The coach said
"You should have been here five minutes ago. There's no outing today!" Strictly speaking he was within
his rights to do that, but I suspected it was an excuse not to have to take us out that day. I also felt he
could have punished the offenders in a number of other ways, but for me that was enough, and I told my
tutor what had happened and how, for the sake of my 'A' Levels, I should give up rowing.

History proved that I made the right decision, but that day also coloured my attitude towards authority. I
still think the spirit of the law is more important that the letter of the law - within reason! Respect
everyone.

## Gun Games with the CCF

I mentioned in passing earlier the CCF, the Combined Cadet Force. In many Public Schools there was, perhaps
still is, a strong link with military. When I doing my PGCE, the grand sounding 'Post Graduate Certificate in
Education', at Reading University, I did my teaching practice at Wellington College. The name alone suggests
military connection, so even Monkton, set up to educate the sons of Christian Missionaries, had its CCF.
There is the expression, 'If you can't beat them, join them' so although theoretically one might have been able to
opt out, in practice no one did. It was all rather gung ho. 'Jolly good fun chaps, this army lark!' Looking back it
was frighteningly like the 'Oh Oh Oh What a Lovely War' attitude which prevailed at the outbreak of World War 1.
Training, on Wednesday afternoons, started with Square Bashing, or Drill. Itchy Battledress uniforms, spit and
polish, literally, of the boot's toe caps, and being yelled at by the Sergeants, many of whom were the dreaded
Sub-Prefects, but now with three stripes on their arms. It was amazing how soon we resembled a moderately
competent fighting force. Drill required a degree of coordinating, and if you didn't have it already, you soon did if
you didn't want to be given even more punishments.
I can still hear the words "STOP T L V RETURN" ringing in my ears. They are the commands for the About Turn
on the march, with the T, L and the V representing the position of your feet. It was a brutal form of choreography,
but nevertheless quite satisfying when you got it right.
Highlights of the CCF year were the Field Days on Salisbury Plain. We were issued with 'Blanks' and played
"Gun Games' with great enthusiasm and lots of noise around the spookily deserted village of Imber. The village
had been taken over years earlier for Army training, much to the fury of its inhabitants who had always hoped to
get their homes back.
In the Summer holidays we were sent off to 'Camp' for two weeks, to one of the regular army training areas such
as Lympstone in Devon, home of the Royal Marines. We engaged in exercises involving landing craft, assault
courses and life in tents, which were inspected every morning for the precision with which your bed, pillow and
kit was laid out. Generally good fun was had by all, unless you happened to be one of the nastier sergeants who,
when making a real dog's dinner of an obstacle on the assault course was given a professional bollocking by a
regular soldier, much to our satisfaction and amusement.
Back at school, trips to the rifle range near Box Hill were popular, perhaps more for the wall paper adorning the
rangemaster's cabin than the prospects of becoming a Marksman. I was quite a good shot and remember with
pride the day I was given my cloth Marksman's rifle which I sewed onto the sleeve of my battledress.
You will have picked up that I quite enjoyed the CCF. This was partly because during my second year, a more
enlightened attitude prevailed, so instead of concentrating exclusively on Infantry training to the exclusion of
everything else, new sections were started. The MT section, or Motor Transport, acquired and old car engine we
stripped down and learned all the parts. By now, even I had been promoted so with my three Sergeant's stripes I
was put in charge of the new Civil Defence section. This involved a journey into Bath where we learned to set up
Field Kitchens with their Earth Ovens to feed the nation in the event of a Nuclear War.
One week we were shown a film which chillingly told us that we only had four minutes warning from the time the
missiles were launched to the moment of impact. The next week, after the training we waited to board the army
truck which would take us back to school. There was a problem with the garage door, but eventually, after
SEVEN minutes, it was prised open. Not a good omen for our survival. It was very much along the lines of Dad's
Army and a sense of humour helped get us through.
To put this period in context, there had been the First World War; we had been born just after the end of the
Second World War, and with all of the nuclear proliferation, the Third World War just seemed to be a matter of
when, not if. It was a scary time. We had the Cuban Missile Crisis, when the world held its breath, and we can
remember exactly where we were when we heard that President Kennedy had been assassinated.
My early musical career was short lived. I couldn't master the Violin. I took one home to practice in holidays, but
all I made was a vile din, so that went nowhere. I only briefly joined the choral society. The attraction of this
society was an annual joint concert with the girls of Westonbirt school, but when the conductor waved his baton
in a circular motion saying "There is someone singing out of tune around here" I knew I was in the centre of his
circle, so I opted out of that too.

However, my musical career took an unexpected turn when a Military Band was set up to play at the CCF's
annual inspection. The first instruments to appear were bugles. I was able to make a reasonably rendition of the
Last Post, or Come to the Cookhouse Door, but then a number of side drums appeared. That was much more
my cup of tea, so I learned to do a drum roll with the drum sticks.
When the band itself was formed there were plenty of volunteers from the competent musicians within the
orchestra, but playing while marching was a challenge. The first afternoon we were told not to worry about
keeping in step, just try to play while walking. Cacophony. Gradually things improved and by the end of the year
the CCF staged a flood lit military tattoo, when the Band of the Black Watch accompanied us.
What I have not told you was the 'instrument' I ended up with. I played the cymbals! With great gusto and no
complaints.
Next time I will explore the unexpected link between army training and natural history. The two photographs I
posted today are relevant, and are there for you to think about before I explain tomorrow.

The six S's and the motorbike.
Unlocking memories from the distant past.
One of the things I have found most enjoyable writing up my memories has been how by recollecting one
particular event has reawakened the memory of another incident I had not thought about for more than half a
century.
'Spit and Polish' was, and probably still is, quite literally how soldiers get an amazing mirror like finish on the toe
caps of their boots. You get a cloth, add boot polish, then rubbing gently round and round for hours, adding spit
from time to time. In time an incredible glass like surface starts to form.
In the weeks leading up to the CCF's annual inspection countless hours were spent (wasted?) on bringing our
boots up to that standard. The problem was, just as you reached perfection it could all go disastrously wrong and
the surface would disintegrate. This happened to one of my pals just before the big day. What to do? He took a
gamble and painted the toe caps with gloss black paint. The inspecting VIP commended him on the high
standard of his boots. Another candidate for SpecSavers?
Yesterday I posted two photographs of Roe bucks with my story and said I would explain their relevance today. I
wonder if anyone has guessed the connection?
Let me explain. One of the topics covered in the army cadet training was Fieldcraft, and in particular how
sentries or patrols can learn to hide from view using camouflage and concealment techniques.
A particular mnemonic was used to teach this - THE SIX S's.
Had I not looked it up, I would never have spelled mnemonic correctly. I would have started it with pneu....., but
thanks to my friend Mr. Google, I can explain what a pneumonic, sorry, a mnemonic is.....
I. What is a Mnemonic?
A mnemonic, also known as a memory aid, is a tool that helps you remember an idea or phrase with a pattern of
letters, numbers, or relatable associations. Mnemonic devices include special rhymes and poems, acronyms,
images, songs, outlines, and other tools. Mnemonic (pronounced ni-mon-ik) is derived from the Greek phrase
mimnēskesthai meaning to “remember.”
So now you know!
In teaching these concealment techniques 'The six S's' were Shape, Shadow, Shine, Silhouette, Surface and
....., well we used the word SHIFT for 'movement'.
I wondered if Google would reveal anything about this concept and to my surprise I unearthed a current Power
Point presentation used to aid field craft training. The teaching technology has moved on, but the basic message
is exactly the same, and it is the principles of concealment in nature which I love. That is why I posted the two
deer pictures yesterday.

The younger buck, whose antlers are still covered in velvet, is standing right on the ridge, clearly silhouetted
against the sky. The older buck is standing stock still in the shadow of a bush. (Can you see how his antlers
have no velvet on them - he'll soon need to use them in earnest this year to fight off rivals who have their eyes
on his ladies, so he has to have his antlers ready for action sooner than the young buck, whose antlers won't be
needed for action for a year or two.)
The other side of the concealment techniques, are the observational skills you need to develop if you are going
to spot creatures (or sentries) who are trying not to be seen.
One year a fox had her family in a den high up on the opposite side of the river but I could get a good view of it
by climbing to the same level on our side of the river. The flat stump of a recently felled tree gave me a good
seat, so armed with my binoculars, I took up a pad of paper to write letters while waiting for the action to start.
On very still evening I was sure I had seen a movement below me. I then saw it again. When I checked it out I
could see a deer's ear. It was attached to the deer, but that was all I could see of the animal, but flies were
bothering it and the ear kept twitching.
The Monkton Combe valley below the school had an attractive stream, known as the Midford Brook. Although
there were trout in the brook, I more often fished for Dace, small coarse fish which shoaled at one particular
spot. One of the masters was a keen angler who took us to a nearby lake teeming with perch of which we caught
plenty. This was a marked contrast with a funny incident on the canal. Richard Cooper (my friend was from the
farm in Burford) and I were walking on the canal tow path when we saw a large perch lying still in the water. Just
further up a couple were fishing, but they had had no luck, so we told them about the fish we had just seen. The
chap pulled up the pathetic drowned worm, purporting to be the bait, and lowered it right in front of the perch's
nose. Not only was the fish totally uninterested, it didn't even move away. Had I been that angler I think I would
have given up.
I want to tell you about badger watching, bird watching and barbed wire, but I will finish today with a story of the
motorbike.
My cousin Judith had joined the staff of Monkton Combe's junior school on Combe Down, just a couple of miles
up the hill. Richard Cooper and I were having tea with her one Sunday afternoon when she told me about a
motorbike one of the teachers had. It was a James Cadet, but the engine's big end, whatever that was, had
broken and he wanted rid of the bike. I had been in the MT section of the CCF the year before so I was keen to
take it apart to learn more about engines. To my surprise my House Master, Vic Baker allowed me to put the bike
into his garage, so we pushed the bike down the hill and removed the engine which I hid under the desk in the
study I shared with Richard Cooper.
We stripped the engine down, found the broken con rod, the bit which connects the piston to the cam shaft, and
ordered a new one. When the replacement arrived we reassembled the engine and everything seemed to fit
back into place. But would it work? To find out we needed petrol, so armed with a screw top jam jar we walked
down to the garage on the Warminster road and were given enough petrol to test is. I think you could actually
buy 2-stroke petrol from the garage, because that is what it needed.
That evening, during the 'Study Period' when we should have been doing our 'Prep' we got engine out from
under the desk, poured some petrol into the fuel pipe, and with Richard putting all his weight on the bare engine
block, I jumped on the kick start. To our horror, at the very first attempt the wretched engine burst into life. With
no silencer the racket was dreadful so I immediately whipped off the spark plug and we stuffed the engine back
under the desk.
As we did so, stomping up the corridor, a prefect was opening the other study doors. "What was that noise?
What was that noise?" I don't think playing the innocent card and asking "What noise?" cut much ice, but luckily
he was one of the decent Prefects and after explaining our project was with Mr. Baker's approval, we got away
with it. Not all of the prefects were mean. Brother David was known to be very fair, and went on to have a
distinguished career in the Police.
The engine and frame were reunited. We test ran the bike up and down the drive behind Hill House, and
eventually the bike made its way to London. I even passed my driving test on it before getting a Honda 90 to
commute from home to college.
Keep safe every one.
