# Mr. Ezra and Mandarins

So the story so far describes how George was able to use his time as a forest officer in the Gold Coast (Ghana)
to collect and study the local animals, and then after the Second World War how was helped by a friend send to
send a lot the animals back to England to restock, London and Paignton Zoos.
This led to an invitation to become Superintendent of the London Zoo in Regents Park.
For my older brother David and myself growing up in the zoo was amazing. It was our home because our house
was in the middle of the zoo. Our immediate neighbours were the hippos, then the giraffes beyond them.
Father was only 38 when he took up his post, and having just returned from fourteen years in Africa he had few
close friends near by, but he was befriended by a number of people who shared his interests.
Children are very accepting of the world around them, so to accompany our parents to lunch invitations was part
of the territory. We didn't ask questions; we just went. One regular invitation was to have lunch with a certain 'Mr.
Ezra', an elderly man who lived in Surrey. He was involved with the Zoo, and had a house near Cobham. A
mansion might be a more accurate description.
The lunches were formal with a capital F. The massive table was set out with the finest silver and glassware.
There were finger bowls and I lost count of the number of courses, served of course by the staff.
Mr. Ezra had a large estate, and after lunch we would walk in the grounds, except I would ride in Mr. Ezra's
invalid chair, crouching down at his feet. It was one of those old fashioned elongated chairs with large wheels at
the back and a single one out in front, and electrified. There we free living wallabies in the grounds, numerous
nest boxes my father checked for occupancy, but apart from that I knew very little else about Mr. Ezra.
Roll on sixty years and one day I am walking beside the burn when I am astonished to see the gaudiest of all the
ducks. A drake Mandarin Duck. (I will attach a picture of one, not one I took myself, so you can see what I
mean.)
Mandarin Ducks are Chinese and favoured by wild fowl collectors for their ponds. I suppose the Mandarin is the
equivalent of Koi Carp. But what was a Mandarin Duck doing in Hartburn? Funnily enough I had always thought
of Mandarin Ducks a being so over the top that they looked unnatural. Even artificial; but when I saw it in its
natural environment I saw how wonderful it looks.
I continued to see a single Mandarin drake for a few years, then a pair, and then a small flock of them. In 2018 I
saw sixteen together a couple of times, and last year my friend and neighbour Gary saw the mum with about a
dozen ducklings. This spring I have see a pair several times, but yesterday I saw just the drake four times. My
guess is the female is nesting somewhere. (Factoids. They nest in holes in trees. They nest late so often suffer
from a housing shortage so their populations only grow slowly, and are about the only non-native species in the
country which causes no environmental damage.)
I have now learned that there is a strong population of Mandarin ducks in the Kielder/Tarset area, One day,
returning from a day out at Kielder Dam I pulled over to allow some cars to pass where the road is close to the
North Tyne. As I glanced to my left I was astonished to see about 25 Mandarin Ducks sitting around on exposed
rocks on the river banks.
By now my curiosity was firmly aroused. Where did all these Mandarin Ducks come from?

Five minutes Googling and I had the answer. "Mandarin Ducks were first kept in this country by the eminent bird
collector Albert Ezra on his estate in Surrey, and the feral population originated from there."
As with so much Googling, you can't leave it there, so I then started probing deeper. Who was Mr. Ezra? Well it's
all out there for you to discover but I'll tell you what I found. Albert Ezra was born in 1872 in India. His mother
and wife were members of the Sassoon Family. Yes, they included Siegfried Sassoon. The Sassoon family were
very successful bankers in China and were known as the Rothschilds of the East.
Click on this link.. https://en.wikipedia.org/wiki/Alfred_Ezra
My memory is that he was just a very sweet old man.
In future chapters I will talk about some of the other characters I encountered.
