# The Duke of Bedford and Some Fishy Tales

My father had a number of hobbies. Sailing, which he was good at but seldom had a chance to enjoy.
Jam, marmalade and chutney making, which he was good at and did regularly, but also he was a keen
and competent fly fisherman.

Through the generosity and kindness of his friends and acquaintances he was often offered the chance
of some excellent trout and salmon fishing - at a time when there seemed to be plenty of fish in the
rivers.

As a boy I enjoyed fishing too, although nowadays I get more pleasure from fish-watching. (I will explain
how this works in a later chapter.)

Father met many interesting people through his work at London Zoo. Some became friends such as Mr.
Ezra. (Yesterday a friend told me how she was so fascinated about him that she Googled him and now
"knows all about him")

There was also an old lady I would love know more about, but despite my best Googling efforts, I cannot
find out anything about her. Miss Maud Nobel lived on the Camden Town side of Primrose Hill. When you
knocked on her door you might have thought it was Battersea Dogs home from the noise. The door
would be opened by her maid, but then the diminutive Miss Nobel would come down the passage
surrounded by a flock of about a dozen Pekinese, all yapping and skidding around her.

That was nothing compared with what was to come. Turn left into the large front room and you were
confronted by literally dozens of cages of parrots of every shape and size. At the time it was almost
impossible for an ordinary mortal to tell whether Amazon parrots were male or female, but Miss Nobel
was of the few people who apparently could. Some year later technology made it easy. An endoscope
was inserted down below and if there were ovaries, the bird was without doubt a lady! (They don't like it
up'em in Cpl. Jones' immortal words.)

But now we come to the Duke of Bedford.

I cannot remember ever meeting him, but he was a keen naturalist and ornithologist, and also happened
to own the Woburn Estate. If you are curious to know more about him just Google '12th Duke of
Bedford'.

No mention was ever made of Duke's involvement with far right politics but in 1953 I remember being
told he had died in a shooting accident. The story I was given was that a sparrow hawk was preying on
his free flying flock of Budgerigars and as he was climbing over a style with a loaded shotgun he ended
up shooting himself. That might have been easier for a six year old to accept than the full truth 'whatever
that was' as our heir to throne might say.

On the Woburn estate there are number of lakes, and one day my father took me out fishing on the
largest lake in front of the Abbey. I was only tiny, but the fish he caught seemed to be monsters, and
vicious. Years later my father told me they were Zander, also known as Pike-perch. Predatory and pretty
ferocious. They were interesting times.

Some time after this we went back to Woburn for an entirely different kind of fishing. In the Chinese
garden there was an ornamental pond teeming with large Golden Carp. We were setting off to catch a
dozen of them for another zoo. 'Where is the rod?' I asked my father. 'We don't need a rod, the fish are so
tame we just need my landing net' he replied.

This turned out to be a significant underestimation of their intelligence because as soon as the landing
net was deployed the fish kept their distance, despite being tempted by the last of our white bread bait.

So it was back to London and a return trip the following week, armed with a rod and line.

Never has fishing been so easy. The moment the bread touched the water a feeding frenzy occurred and
within no time had a dozen large fish in the tank of water we had in the back of the estate car.

However, among the massive carp there two tiny ones. Well, relatively tiny compared to the carp, maybe
about five or six inches long. David and I were told we could have them if we could catch them. This
proved to be challenging. We had to wait until they were well away from the monsters, then cast
accurately to give them a chance to take the bait. Time and again, just as the target fish was about to
take the bait a big one beat him to it. I cannot think of any other fishing experience when one was
annoyed to catch the larger fish. Finally we were successful and the two goldfish lived for many years in
a tank in our garden in London.

Another chapter on fish and fishing will have to wait.
