# Pets at Home

In 1953 our move from the Zoo to NW2 was only a few miles. Walking distance from Hampstead heath,
but on a route which offered equally good access to the West End and to open countryside.
This six bedroom semi- accommodated the family, my father's live-in secretary, my mother's European
au pair girl but in the custom built, insulated shed in the garden, my father's collection of pets. Some
common, some exotic.
In the house was our much loved tabby cat, Popa, named after the Mexican volcano, Popocataptl, and
the Liisa, the Finnish Spitz. A lovely dog, but its other name of the Finnish Barking Dog should have
warned us that it was perhaps not the best choice when surrounded by neighbours. In Finland they run
ahead of hunters and bark at base of trees into which game birds have sought sanctuary.
In the dining room was my budgie and a re-homed African Grey Parrot. In the drawing room my brother
had tropical fish, and in the garden itself one or two tortoises, The Blue Peter tortoises lived with us;
First there was 'Fred' He became 'Freda' when he, sorry she, laid an egg. For a while the second Blue
Peter, George also lived with us. After the fishing expedition to the Woburn Chinese Garden pond, the
two anonymous gold fish joined the family.
It was in the garden shed where things started to get more interesting. The cages always contained a
range of common pets, Netherland Dwarf rabbits, Guinea pigs and White and Hooded Rats.
There were always at least two snakes. A Royal Python, also known as the Ball Python, with its most
beautiful markings, and an African Python, which tended to grow and grow and grow. These were joined
by a Boa Constrictor. All of the snakes were handled regularly and taken by my father when he spoke to
schools, clubs or Women's Institutes etc.
The star of the show was Polly, my father's Bush Baby. My father had Polly for many years and she made
countless appearances at father's lectures. If the audience was large he would take Polly to the back of

the hall and put her on someone's shoulder. He then walked to the front of the hall, where Polly would
rejoin him having jumped from shoulder to shoulder the entire length of the hall.
Those were the residents. We then entertained 'animals in transit'. B&B you could say - in boxes or
behind bars! You never quite knew who would turn up, or how they would arrive. It seemed that anyone
with an animal they no longer wanted would ask George to re-home them.
On day a couple turned up with a monkey. The wife was in tears as she got into the car to leave, but
before her husband left he whispered into my father's ear, "I'm so glad to be shot of that wretched
creature. She would bring it to bed with her!"
I have just remembered how one of the tortoises arrived. It just had a piece of newspaper taped around
its shell with the head and tail poking out at either end. I cannot recall who delivered it, but I think it was
the postman himself. Full marks for imagination to the sender. It was better than dumping it as some
irresponsible exotic pet owners do today.
Although it was my father's secretary who helped look after the animals in term time, when David and I
were at home we helped too. Father was a keen gardener so all the soiled bedding went on the compost
heap. Horse drawn carts were still used by the rag and bone men, the recycling operatives of the day,
and from time to time they would come round offering a load of manure for gardens. We delighted in
saying 'We make our own!" which never failed to raise their eyebrows.
One weekend we looked after a lion cub in transit to another zoo. Then for a few days a delightful black
bear cub was staying. He was very tame and could be walked on a lead. The current au pair girl was
animal mad and took it for a walk to the shops on Finchley Road. She returned home in tears.
Apparently nobody had shown any interest in young bear even when she started stopping people and
telling them what she had. I still think it was so strange.
One day a new au pair girl had just arrived. It was a warm summer day and we were having a cup of tea
in the garden. Suddenly she too burst into tears! A tortoise was approaching her chair.
To my mother's horror she realised she had forgotten to mention we had animals, and this poor girl
appeared to have an animal phobia. The offending tortoise was removed to a safe distance and since by
good fortune we didn't have any animals in house itself at that particular time there was a possibility
things might still work out, provided no mention was made of some of the residents in the Animal
House.
In the event, an animal-free family was located and the lass would go to them after a couple of weeks.
During this time she actually got used to the tortoise and was not bothered by the fact that there were
animals in the garden shed. She didn't need to go in there. It was shortly before leaving that she
discovered the awful truth. "You never told me you had SNACKS!" were her immortal words.
It was sad that a few days later she did move on because by then she was already less worried by the
snakes in the shed and given a little more time she may well have stayed. On a number of occasions
father cured people of their irrational fear of snakes, but you can't win them all.

I had been given my first Budgie by Mr. Palmer, proprietor of his big pet shop in Camden Town. He was
blue (the Budgie, not Mr. Palmer), and I called him Winky. In time Winky died and was replaced by a Grey
green budgie, Smokey. One day I was in front of the house only to see Smokey sitting on the fence like a
mugwump. (I'll explain in moment if you've not heard of a mugwump.)
I didn't want him to fly off so I approached him slowly, offered up my finger, and as he alighted I
deployed my thumb to hold him down - and I had him. I took him into the house, only to find Smokey
was still in his cage! It wasn't Smokey at all. I now had two. I think we must have put a sign on the gate
telling people that we had found him because we didn't keep him long. No social media in those days.
Unlike today, house sparrows were very common in our gardens. Their cheeky chirping call was imitated
by the budgies who I suppose had Cockney accents. The sparrow caused havoc in my dad's vegetable
garden, so he gave me an air rifle. Did a lot of target practice but the best way to scare off the spuggies
for me to place old tin cans and buckets in the garden and then fire at these targets.
On hot days the Animal house doors and windows were left wide open, and one day the Royal Python
was missing. Strangely its tank lid was still secure, but we searched high and low to no avail. All the
pythons were called Percy, plus an adjective. This was handsome Percy.
A few months later I went into the Animal House. The doors and windows were closed, and there, curled
up on top of the snakes' tank was Percy. He was in good condition and must have been returned by the
thief. A mystery we never solved, but I wonder if someone in the thief's family discovered where he had
come from and demanded the perpetrator took it back. Years later I had another stolen item returned in
the strangest of circumstances. That can wait for another day.
Almost forgot. Mugwumps? “The first political mugwumps were Republicans in the presidential race of
1884 who chose to support Democratic candidate Grover Cleveland rather than their own party’s
nominee. Their independence prompted one 1930s humorist to define mugwump as ‘a bird who sits with
its mug on one side of the fence and its wump on the other’.”
David had his tank of tropical fish in the drawing room and from time to time we went to the pet shop in
Hendon to get some new ones. To collect them, and keep the water warm for the journey home we filled
one of our mother's shopping bags with large glass Kilner jars, plus a hot water bottle for warmth.
The bag was quite heavy so we had a handle each.
The bus stop on the Hendon Way, a dual carriageway, was about one hundred yards short of a busy
intersection with Cricklewood Lane. As we waited to cross the dual carriageway we saw the bus coming
down from Finchley road, but we didn't get to the bus stop in time. Luck was on our side because the
lights turned red and the bus was forced to stop at the cross roads.
Not wanting to wait for next bus we sprinted for it. David was faster than me and leapt on board just as
the lights turned green. He held onto the pole with one hand and the bag handle with the other but the
bus was now travelling at a considerable speed. David pulled his handle as I pulled mine, and by a
miracle I took a final leap onto the bus' platform. Exhausted and out of breath I collapsed onto down a
back seat.
