# The Eagle Has Landed and Family Fortunes

If you like jigsaws you will know that is only as you start fitting the pieces together that the picture starts
to emerge. But then there is that irritating gap you just can't fill. You begin to think the piece you need
has been lost, but suddenly there it is staring you in the face all along.
One of those missing pieces was the one which explained how my father was able to afford our school
fees.
In the 1950s and 60s there was a popular comic called The Eagle. From the internet I have discovered…..
The Eagle, one of Britain's most famous and well remembered comics, was launched by Hulton Press on
14th April 1950. The brainchild of the Reverend Marcus Morris and artist Frank Hampson, Eagle was
created to promote Christian values and provide an alternative to the American comics which Morris
considered to be well produced but morally repugnant. The lead character, drawn by Hampson, was Dan
Dare, a square-jawed space hero.
If you would like to know more here is a link……
https://britishcomics.fandom.com/wiki/Eagle_(Hulton_Press)
My father was a regular contributor to the Eagle, with half page articles which were all entitled “Nature
had it First”. I used to read the comic, but to my shame I probably took my father's column for granted
and went straight to the Dan Dare stories. One day, not long before he died my father remarked in
passing that his work for the Eagle had paid for David's and my school fees
I have copies of most of the books he wrote but all of our ‘Eagles’ disappeared years ago. I felt bad
about this and didn’t think I could do anything about it, but from time to time I buy things on eBay. If you
type ‘Cansdale’ into the search bar and click on ‘Books, Comics and Magazines’ you'll instantly be
offered scores of books, most but not, all written by George.
One day I want to buy a copy of his Ladybird Book of British Wild Animals. This has the most attractive
paintings and was held up by Chris Packham at the very start of a recent programme documenting the
history of Ladybird Books. To my delight and astonishment I saw someone was selling six of my father's
articles from the Eagle. I messaged him and wondered if he would do a deal if I bought them all. He said
he was very happy to do so, and then explained how he had been one of my father's fans and had cut
out these articles from the Eagle comic years ago. He sent them to me but then a few weeks later he
contacted me again offering me another 50 more for a nominal price. He then found the rest of his
collection which he offered to me on the condition that they would be a gift and he wanted nothing for
them. There are some wonderfully generous People out there.
Today I sorted them into their different categories. I now have 133 in all, covering British birds, Insects,
Prehistoric Animals, Life Under the Sea and Pets. In fact there are only four ‘Nature Had it First’ articles
which I had mistakenly thought were the majority. I feel humbled not just by his amazing breadth of

knowledge and his ability to share it so enthusiastically, but by the fact that all that hard work had
funded my schooling. I hope we showed him our gratitude before he died
In my title for today's ramblings I included the words ‘Family Fortunes’.
My paternal grandfather was a Cockney who worked as a clerk for a shipping company in the London
docks. His father had grown up on a farm in Essex but his experience with horses allowed him to get a
job in London driving carts for the Royal Mail. But it was my grandfather's uncle’s job title which really
takes the biscuit. When he was 14 there was a census in which his profession was stated as……..Well, I
would really like you to have a guess. It is a job which while certainly important has perhaps the lowest
status of all the jobs on the farm. I'll give you a clue. When I was working with African agricultural
development projects I often saw small boys doing this job as harvest time approached.
I'll tell you “Rook Scarer”. My great great uncle was a Scarecrow!
The fact that within two generations my aunt, my two uncles and my father had all achieved significant
success in their lives is a great tribute to my grandfather, a devout god-fearing man, who believed in the
importance of education.
I will finish with an amusing conversation I had with my father after visiting my 94 year old grandfather
at the care home he lived out his days at Frinton on the Essex coast.
I can work out his age because it was before I passed my test and I was driving my father’ Vauxhall VX
490. It was a nippy car and there was I, still with L plates and before any speed limits, driving at 80 mph
most of the way back to London. Scary thought. Sorry, that is irrelevant to my story. The conversation
went like this.
Father. “Grandpa is very worried what to do with his money.”
Me, slightly embarrassed at having to ask. “Is there very much?
Father. “About £4 7s 6d, or £4.37 in our coinage.
My father had very humble roots, which make his achievements all the more remarkable.
If you remember the Dan Dare stories you will remember the Mekon too.
