# Prep School High Days

For the first two years after moving to Lyndale Avenue I remained at my Primary School, North Bridge
House. I have a handful of disjointed memories of this period. David had already left for Great Walstead,
a boarding prep school near Haywards Heath in Sussex. One girl in his class was a certain Jane Asher,
who achieved fame as an actor, a friend of Paul McCartney and the maker of wonderful decorated cakes,
which Zoe emulated. My special friend at the time was Belinda, a class mate who I was very fond of
when I was six and seven. I wonder if she is out there somewhere, but I fear, even if she is she wouldn't
remember me.
For the next two years I traveled the three miles to and from school, alone on the London buses; from
the age of just six. Would the parents of today allow that? I doubt it. I would pay my tuppence, and on
way home hoped not to fall asleep because my stop, Child's Hill, was a request stop and I had to ring the
bell to stop the bus. I have just remembered how one day when we were still at the zoo my mother came
to collect me she took this little boy in his school uniform by the hand and led him off, only to realise to
her horror she had hold of the wrong child. Do I recall a SpecSavers ad to that effect?
Before joining big brother David at Great Walstead my parents and I drove down to see him, as I recall it
only once, or possibly twice a term, to take him out for day. I can't remember anything about the visits
themselves but still recall all too clearly how we were involved in a nasty accident on the way home
when a motorcycle drove into the back of our car at speed. The image is still clear in my mind. We were
invited into a house for a cup of tea, and I am afraid the motocyclist lost his leg as a result of the
accident. None of us was hurt but our car was a Morris Isis estate car with two backward facing seats in
the very back of the car. I often sat there, pre-seat belts of course, but on that journey I opted for the
standard back seat shortly before the crash. Had I not moved I would probably have been injured.
I had been very happy at North Bridge House, but being sent to a boarding school having just turned
eight was....... Do you know I actually find it hard to find the right word. It was certainly a shock to the
system, but I coped and soon settled in and started to enjoy the freedom which allowed us to roam
freely on the school's farm and in the woods. I was one of only two new boys that summer term and
given the number 81. The first time the number had been issued, so that term there were just 81 boys.
While on the subject of numbers, a few days later I remember the teacher writing the date on the
blackboard. It was 5th May 1955. 5/5/55. (Twenty two years later I taught my very last lesson on the 7th
July 1977. 7/7/77.)
It was early that first term when I passed a hedge in which I saw two long tailed tits, so close I could
almost touch them. What amazingly beautiful birds they were. This was my first, personal wildlife
experience and the start of my love of birds.

I didn't appreciate it at the time, but this was not your average prep school. For example, if you broke a
window - you mended it. You would be given glass of the right size, the putty and the necessary tools,
and shown how to do it. I only had to repair a window once but the reason I recall it so clearly was
because I cut my little finger very badly and it was only a few years ago when the scar eventually faded.
All the lawns around the school were mown by the boys using a variety of petrol engine mowers, which
we also maintained. Boys from farming families drove the little grey Massey Fergie tractor towing its
gang mower to cut the playing fields. The most lethal machine was an Allen Rototscythe. Two large
tyre-less wheels drove this monster with a bar of vicious reciprocating triangular blades. At least the
lack of a silencer meant you could hear it coming from a mile away and nobody, to the best of my
memory, suffered a double foot amputation.
If that wasn't enough potential danger there was plenty more to come. We could use our axes to chop
down silver birch trees to make camps and dens in the woods. Tree climbing was permitted, and it was a
right of passage to climb to the top of the Big Fir, a mature Scots Pine tree close the school itself. I
attach a photo I took from the top looking down onto the school. Some years before my arrival the
headmaster, who by now you will have appreciated was a touch eccentric had constructed a mini-roller
coaster, known as the Switchback. It was in a poor state of repair so not often used but there was still
one potentially dangerous bit of fun to be had.
Mr Mowll, the Head, had stripped down an ancient car leaving just the wheels, the bare chassis and the
steering column. From the school to the kitchen gardens there was a winding farm track with perfect
gradient for this madness. Seven or eight of us would commandeer the chassis. With one boy steering
and the rest of us hanging on for dear life, we would career down this track. We then pushed it back up
the hill and repeated the exercise with another boy at the helm. Amazingly, I do not recall any significant
accidents from our free range activities.
Up in the woods there was a tiny stream, not more than a trickle really. Here dam building was serious
stuff. The older boys' earth dams were upstream so when they opened the flood gates the dams further
downstream were inundated and destroyed.
I was far from academic. In fact without exception I was always one from the bottom of the class.
Howard Smith III, so named because he had two older brothers at the school, was always bottom. (Not
his real name.) By the same token I was Cansdale II, or 'Canny' to my friends. I thought being one from
bottom was my pre-ordained position in life and I could to nothing to change it, so I didn't. It wasn't until
I was about fourteen that I discovered that with hard work I could do a wee bit better.
The school was run as economically as possible. Mr. Mowll love auctions where he could buy up army
surplus materials for knockdown prices. At one Prep School Headmasters' conference when all he other
heads were complaining about having to put the fees UP, Mr. Mowll proudly boomed out "I have just put
my fees DOWN!" Thinking back now, I suspect German or Italian prisoners of war might have had better
rations than we did. Luckily the gaps in the floorboards in the 'Dining Room', in reality just a large shed,
were wide enough to drop the slices of inedible cold beef through. There were few if any oversize boys
in the school.
Sussex had been on the front line during the Second World war. Stories of the Doodlebugs, the VI flying
bombs being intercepted overhead were still being told. One had allegedly landed in the local village
duck pond. Instead of Cubs or Scouts, the school had its equivalent in the form of Mudlarks and Q Day.
Q Day was a protracted war game on Wednesday afternoons. In the summer term, the climax was a 24
hour exercise when we slept in the camps we had been constructing. This was Q DAY itself. We never
knew when it would be, but a code word was given to a senior boy, mid lesson, at which point he would
shout out "Q Day!". School lessons would be abandoned and 24 hours of sleepless mayhem would
follow. All good fun.
Despite all the freedom, discipline was surprisingly strict too, and misbehaviour was still generously
rewarded with corporal punishment. Often it was deserved, but not always. One term there was a
marbles craze. Everyone was playing marbles and if your were any good, you could build up a good
collection. One evening, after lights out, I needed my handkerchief from the pocket of my shorts on the
chair beside my bed. As I pulled the handkerchief out of the pocket all my marbles cascaded onto the

floor. A horrible shiny hardboard floor, no doubt the cheapest way to cover dormitory's old floorboards
to avoid splinters. As my marbles rolled in every direction they made a terrible noise. A master had his
bedroom next to our dorm. He stormed in, demanding to know whose marbles they were, and without
any chance to explain I was slippered. Today that would be classed as an assault. 60 years ago it was
part of the territory. We accepted the rough with the smooth. One boy was once playing with a toy
aeroplane he had lovingly made from balsa wood during a lesson when the teacher caught him. His
punishment? He was told to put in on the floor and stamp on it! Ouch. Harsh, but I bet he never did it
again.
Curiously it was in that very same dormitory as the new term started that one of my pals produced a
strip of material from his pocket and said "Look what my uncle has invented." It was strip of Velcro.
I was happy with the freedom but I did not thrive academically. The class I joined had studied French for
two terms. I had none, so when in my very first French lesson I was asked to read aloud from the text
book 'Ou est ma femme?' I tried my best and said 'Oo est mar femmy!' the class fell about laughing.
There and then I decided 'French is most certainly not for me.' Latin was equally disastrous.
On balance, am I glad to have been sent away to school so young? Given the circumstances I guess I
am. I preferred the countryside to life in London. My parents were both exceptionally busy, but in the
holidays had plenty time to do things with us. They were loving and kind, and I am sure they did it for us
and believed it would be good for us. I never once
abandoned.
One factor which I had forgotten all about until talking to David, which may well have had a bearing on
their decision, was air quality.
London in the 50's and even the early 60's was plagued with smog, particularly in the winter. I only
remember one really bad one, and that was before we left the zoo, but boy it was bad. It must have been
the smog of December 1952 which lasted for five days. That year 10,000 people died in London from the
air pollution. Some years later a newly arrived au pair asked my mother "Where is the fog?" Such was
London's reputation at the time.

Some people believe that I have a good memory for dates. They might have that impression because
that several of the landmark dates in my life, by which I mean those key events involving house, school
or job moves were actually on dates easy to remember. So my Great Walstead years were 1955-60,
Monkton Combe 1960-65, London University and the Lake Chad Expedition 1965-1970. I actually flew
home from Africa having left Lake Chat and hitch-hiked across the Sahara to Algiers on 1st January

1970, so I might be able to remember easy things. Remembering to put things away in their right places
is not.
While writing about my time at Great Walstead opened the door into more memories. When I joined the
school as an eight year old there were only just over 80 pupils. It was more like an extended family and
you very soon knew who everyone was.
Because very early on, probably from the very first week I had decided I was not very good at lessons, I
don't think I was motivated to work hard. To have joined the school in the summer term was, with
hindsight not a good move. I still have no idea at all why I did that.
Learning was not helped by the fact we were expected to master writing with the ghastly nib pens
dipped in home made ink. History lessons were about learning the names and dates of irrelevant kings
and queens. That was bad enough but on history exam I will never forget. I might have been nine. We
were given a sheet of paper to write on. The paper was never top quality but the sheet I was given was
unbelievable. It would have served its purpose better as blotting paper. All I can recall of that exam was
the vile ink being absorbed by the paper and spreading out to make wonderful flowery patterns. I
probably got none of answers right.
We all seemed to have permanently ink stained fingers, and yes, we used those china ink wells you
dropped it the little holes in the wrought iron and wooden desks with lift up lid. I gather these are now
popular curiosities picked up in auctions. Many will have the names of former occupants gouged into
the wood and stained with ink. I am sure out there somewhere is one with the name W.Churchill
engraved in the lid. It would be worth a fortune. Do I remember correctly that Winston was not an
academic either?
My first brush with authority was over an altercation in one of these desks, I think in my first term. It was
a double desk, semi-detached you could say. There was a bit of shoving and pushing going on but my
shove was sufficient to propel my pal out of the desk and he ended up on the floor. (This was in a lesson
of course!) I don't remember what the fuss was about or who started it, but I got the blame and was sent
to the Headmaster, Mr. Mowll.
Terrified I retreated to the loos, and then went back to the class, having said that I had seen him. I was
not street wise enough to realise the teacher would speak to the head later, which she of course did.
This time the retribution was swift. The cane. I think it was six strokes. Was I emotionally damaged? I
don't think so. Did it stop my mischievousness or make me into a 'goody goody'? No on both counts.
I was not the only creature to be on the receiving end of Mr. Mowll's wrath, but for the others it was more
final. He waged war on his namesakes. Moles. If anyone saw an active mole heap, with the soil being
pushed up to the surface, Mr. Mowll was to be told. He had two techniques to deal with these
unfortunates. The first was to tiptoe up to the molehill and then blast into the top of it with his 12 bore
shot gun at point blank range. The other was to used a croquet mallet, and rather like the way I split
logs, whack it down onto the heap. Both techniques stunned the poor victim who was dug out and dealt
with.
I was caned, slippered, plymsoled and on one occasion struck with a hairbrush by an enraged teacher,
but never hit with a coquet mallet or shot. Be thankful for small mercies.
Before leaving Great Walstead I will tell you of some of the highlights in the school year.
On Shrove Tuesday we had pancake day. No races for us, this was a free for all, rugby scrum, in short a
fight.
Initially it was class by class. The class would assemble in a tight pack behind Mr. Mowll, who with his
back turned, lob a large pancake into the throng. We pounced on it and whoever after a couple of
minutes pandemonium had the most was the winner. This was repeated class by class, but the climax
involved the entire school. I cannot remember any rules or injuries.
Swimming. The swimming pool had been dug some years before I arrived. It was a no frills concrete
lined hole in hole in the ground, but perfectly functional and I quickly learned to swim in my first term.
One of the few accidents I remember was older, large boy coming a cropper on the spring board. The

details are vague but somehow he lost his footing and crashed down onto the edge of the pool. Ouch. It
still makes me wince, but I don't think he broke any bones.
At end of the summer term we had the swimming sports. They ended when handfuls of coins were
thrown into the pool for us to dive down to retrieve. When we returned to school after the summer
holidays the pool was emptied and scrubbed out. There was no shortage of helpers because there were
still some coins to find.
Fireworks on November the Fifth were the highlights of the winter term. A large fir tree would be felled in
the woods, carried back to school by a gang of boys and set up as the centre pole around which the
massive bonfire would be piled.
As with so many things Mr. Mowll had an imaginative way to do this. He had acquired one of those
mobile fire fighting ladders, mounted on two vast wheels and counterpoised to keep it up. This was
placed in position and with a group of boys sitting on the base, a line of boys up the ladder passed up
branches to build the fire. Cunningly a tunnel was left at the bottom, so before the fire was lit on Bonfire
Night ample flammable materials were inserted into the bowels of the heap to ensure a successful show.
A cry went up when centre pole finally burned through and fell over.
Christmas was taken very seriously with the main school hall being decorated, a massive Christmas
Tree, special meals and a carol service. It was an exciting and happy time.
Overall it was a very happy school and by a miracle I scraped though the Common Entrance exam so at
13 I went on to Monkton Combe School near Bath.

Prep School Days and moving on.
I don't have an obsession with fire engines - honest, but after telling you how we constructed the
mammoth bonfire for Fireworks night and mentioning the large wheeled ladder we used, I hunted the
internet for a picture or two. I was astonished to learn these amazing devices had been made by the
Merryweather company even before internal combustion engines. Have a look at the pictures. i have
also added some fuzzy black and white pictures taken with my very first camera, of a Sports Day and the
Swimming Pool.
So how did we get to and from Great Walstead? Haywards Heath is on the London to Brighton line, so
the London based boys gathered on the platform at Victoria Station to board the train. I think the
excitement of seeing your pals outweighed any separation anxiety and usually the journey was
uneventful.
One January that was not the case. The weather was exceptionally cold and the train suddenly stopped.
The points ahead were frozen. The train went back, presumably to find a way around them, but stopped
again. By now the points behind us were also frozen. It was my brother who reminded me of this
incident. We were on the train for several hours as it shuttled back and forth on a short length of track.
During that time we ate every biscuit on the train but to occupy us we tried to think of as many words as
we could ending with the letters -age.
Mr. Google tells me there are 441, that is not even counting the -idge ending words. Being little boys our
vocabulary was pretty limited so along with the Ice age and the Stone age, we came up with the Cab age,
Sew age and Spin age. I don't know if even the scientists had discovered the Bacteriaph age, and were
were much to young to worry about the Remortg age and we knew nothing of Bond age. Nevertheless it
was a good way to pass the time and would not be out of place today with families cooped up with
children looking for imaginative things to do. Word games are a great way to explore the richness of our
language.
Luggage, pun unintended, was sent ahead by train using a system we knew as P.L.A. Passenger
Luggage in advance. David also reminded me that for a while Mr. Mowll rigged up a pulley system to
hoist our full trunks to the top of the building, with a long rope attached to his car which he then drove

across the lawn. I don't remember this myself but it would have been typical of his ingenuity. Perhaps
some things were just too hazardous even for him.
The deputy Head, who went on to be Head after I left GW in 1960 was Gordon Parke. He was a wonderful
man. Considerate and wise. He and his wife lived in Walstead House, away from the rather forbidding
main house. Senior boys spent their final year in smaller dormitories with the Parkes in Walstead House.
The atmosphere was so much more homely and I remember this as a very happy time.
My school reports always had the word 'Excellent' in them. Unfortunately it was normally only once, and
that was under the heading 'Health'. Academically my achievements were nothing to write home about.
But I had learned a lot about Natural History by being having the freedom to explore the woods, the
River Ouse, and farm. We all joined in picking the potatoes (using the school's fire buckets), and helped
with the milking in the farm. Somewhere I have a picture of me riding cow. The skill was to get on when it
was lying down, and then stay on as it stood up.
Sports day was taken very seriously by some. I was fit, but not exceptionally sporty or athletic. To be
honest, competitiveness of any kind normally does very little to excite me. However, Mr. Mowll also
recognised this, so on Sports day some of the races were certainly unconventional. The Fathers' race
was one such "race". One year the challenge was to construct a wooden box from six pre-cut shapes
using a hammer and nails. I don't think my dad and I won that one, but the next year we did, in style.
The Fathers' Race we won had an animal theme - of course! It was called 'Horse and Cart'. The son was
the horse in front, blindfolded with large paper bag on his head and a piece of string, the reins, tied to
each arm. The idea was for the father to use the reins to steer the son the 100 yards down the course.
Just as we were about to set off Dad whispered in my year "Just run as fast as you can!" I checked that I
was pointing in the right direction and we just legged it. At the very finish I collided with a spectator but
we won by a furlong. I think it was the only race we won. Our prize, I have just remembered was a small
battery operated vacuum device for taking dust and hairs of your clothes.
So my days at Great Walstead ended. I just scraped through the Common Entrance Exam to get to
Monkton Combe School near Bath, where I would once again be with my big brother David. Poor chap,
he couldn't escape me for ever. It would be another year before the little grey cells were finally activated.
That story is next.

* * *

Have a good day everyone if you can. I know all too well the pain of losing your nearest and dearest, so
my thoughts are with all of you who are worried about family members who are, for whatever reason,
particularly vulnerable to the virus.
Hang on in there. The dawn will come.

A life saving decision; recollections from Family Holidays.
I was blessed to have the most wonderful mother. I have said very little about her so far, but in due
course I will tell you about her. Perhaps those of you who knew her might like to tell me of your
memories of her which I will gladly weave into my story.
But this morning I will mention how she undoubtedly saved my life one day at Southwold, that very
genteel resort on the Suffolk coast. (Until two minutes ago, when double checking it was in Suffolk and
not Essex, I didn't know it was also on a River Blyth. Yesterday I needed to collect some textile to be
sewn into long filter tubes to renew the sea water intake for the Great Yarmouth Sealife Centre, when I
crossed our Northumbrian River Blyth. Just one of those curious little coincidences which seem to have
peppered my life.)
So what happened in Southwold? I was about nine when we were together on the beach. Mother was on
the shore and I was playing with a beach ball in the water. I had learned to swim the previous summer,
and with the beach dropping quickly into deep water I was out of my depth.

The beach ball was only a few feet in front of me, but as I swam to get it she called to me very calmly, but
with a serious tone in her voice "Let it go. We will get another one." Those eight words saved my life. I
swam to the shore and when I turned round the beach ball was fifty yards off shore. My mother had seen
how an off shore wind has whipped up and was taking the ball out to sea. I would have been determined
to get the ball, and even if I had I would not have been able to swim with it. My mother had assessed the
situation and her quick thinking saved me.
When Jamie and Zoe were growing up I would often say to them, 'there may be times when your
immediate obedience might save your life. Please obey what we say, then you are welcome to ask us we
told you to do it, and we will explain.'
It was that experience in Southwold which taught me that lesson.
Our Pembrokeshire holiday accommodation was far from salubrious. We had two caravans side by side
on a farm near Whitesands Bay. A budget holiday without doubt, but one day I was in the smaller one
when I heard squeaking from outside the back window. A family of weasels were playing around
immediately below me. That was still the best view of weasels I have ever had.
We visited St. Davids, the tiny fishing village of Solva, but also took a boat out to the island of Skomer.
Ten years later I spent a wonderful week on Skomer with friends from London University Natural History
Society. On that occasion the boat's engine broke down on the longer return journey to Milford Haven
but the captain was too proud to call out the lifeboat.
Eventually he started the engine, but by then we were thoroughly sea sick; but at least I am still here.
In 1955 I saw Scotland for the first time. The destination was the tiny village of Arnisdale, on Loch
Hourne. I have just checked with AA Routes. The distance is 593 miles, and even with our modern
motorways, expected to take 11 hours and 5 minutes. I just love the '5 minutes'. That August it took us
24 hours. Literally. The car was a Morris Isis estate car. We had had a Morris Oxford before that but,
although it looked the same, this was the more powerful six cylinder version. Beds were made up in the
back so over night David and I slept for much of the night.
What I have not mentioned was the storm. The weather was atrocious for most of the journey but as we
neared our destination it improved and we had pretty good weather for the holiday, as I recall.
Although this was 65 years ago my memory tells me this was one of the best holidays we ever had.
Where do I start? I saw Golden Eagles for the first time, circling over the hill behind us. (Beinn
Sgritheall). Father approached the owners of the 'Big House' who gave him permission to fish for
salmon on the short Arnisdale river. He did catch one on with a Devon Spinner, but I was beside him
when a large salmon followed the lure right to the bank but didn't take it before father ran out of space
and had to cast again.
Two miles up river are two small lochans. We took the rowing boat onto one of them and caught a lot of
small trout. While on the water a small shower came over so for a few moment there was rain on one
side of the wee lake, clear on the other and bright rainbow overhead. What small boy could fail to be
impressed?
Despite the earlier storm, the north of Scotland had been dry for weeks and the rivers were low and very
clear. As we stood on the road bridge over the river near Glenelg we could see a handful salmon below
us facing upstream waiting for rain. I was the first to look over the other side of the bridge, where
dozens and dozens of salmon were lying shoulder to shoulder. Another sight I have never forgotten.
Although we didn't go onto Skye we did take the steamer one glorious day. The gulls following the boat,
bright white against the deep blue sky, and the best ice cream I had ever eaten were what I remember
best
I don't know if father consulted the tide tables when booking these holidays. He may well have done
because I remember beach combing at the extreme low spring tides. I'll tell you about that tomorrow.

* * *

I must stop now, and we've not even got to Chagford yet. I am sitting up in bed but my back is starting to
ache which suggests I have written more than enough for you and for me for one session.
Today is Good Friday. It will be a strange Easter this year. 2020 the year of the pandemic which will
perhaps go down in history like the Great Plague. Do you remember, (not personally but from the history
books) how it ended? The Great Fire of London! There's a thought for you to ponder.
Keep safe and hope to see you on the other side.
