# Monkton Combe and the Big Freeze

I mentioned earlier that upon leaving my Prep School in Sussex I just managed to scrape enough marks
together in the Common Entrance Exam to be accepted by Monkton Combe School, near Bath in
Somerset.
That is the truth and I can tell what happened. Approximately sixty boys arrived at MCS in September
1960. All but nine went into the Fourth Form, and would take their 'O' Level exams after two years. Nine,
myself included, were unceremoniously dumped in the Third Form. We were expected to need an extra
year to catch up. I accepted my place in the natural order or things and I believed I was 'thick'. At Prep
School I had always been one from the bottom of the class. What was new?
At the end of that first term, six of the nine were moved up into the Fourth Form, and just three, myself
included, stayed in the Third Form. In January '61 more boys arrived, and then a few more in the
Summer term. Life in the Third Form wasn't too bad. I detested the Latin and French, but otherwise did
enough to get along. I was not a rebel; just under the radar.
In September '61 we all moved into the Fourth Form, and during that term we started preparing for our
'O' Levels in earnest. These were the equivalent of the GCSEs of today. Our two Science subjects were
Chemistry and Physics, both of which I found interesting. In Physics we disappeared into darkened
rooms and played around with lenses, determining their focal lengths and creating wonderful spectrums
of colour using chunky triangular glass prisms. It was great fun and the Physics Teacher's catch phrase,
was "Units Laddie. What are they? Pink Elephants?" if you failed to write down the correct units, be they
seconds or millimetres, with the numerical answer.
But in Chemistry there was this mysterious thing called VALENCY. Why was was the 2 in 'H2SO4'
(Sulphuric Acid) or the 4 for that matter. Why was Hydrochloric Acid HCl and not H2Cl if water was H2O.
It was all very very mysterious.
I don't know how it happened, but one day the scales simply fell from my eyes and I suddenly
understood the concept of Valency. It became totally clear to me; almost easy. I don't think I had ever
had an experience like this before. Perhaps I wasn't so thick after all.
The year group was split into sets, A, B and C. So it was perfectly possible for someone to be in A set
for French, but in C set for Maths and the sciences. Guess where I was? Yes, C sets, right across the
board.
Towards the end of that term we all set the same exam paper, but when the results were posted on the
notice board, the chemistry staff had put all three sets' results on the same sheet of paper in three
vertical columns. 'A' Set on the left, 'B' Set in the middle and 'C' Set on the right. I have used our noble
Government's Coronavirus update's envelope to show you a very crude graphic of what that sheet
looked like. (As you know I like re-cycling!)
I will explain. Our names were ranked in order, approximately level with the percentage achieved. As
expected, the scatter of results was pretty well in line with expectations, with the 'A' set results at the top
of the rankings, and the 'C' set at the bottom. But hold on, whose result is circled in orange? One of the
'C' Set results is right at the very top, level with the top marks of the brains in the 'A' Set. Yes, that was
me! I think I had the third highest mark in the year.
The following term I was moved up into the 'A' Set for Chemistry and Physics. Other than French, which
I fully expected to fail, I passed all my 'O' Levels. I then did my 'A's and passed all three, Biology,
Chemistry and Physics, and got my place at Queen Elizabeth College in London University.
I am sure a lot of us will be able to relate to this story; if not for ourselves, for our children or
grandchildren. Tell a child often enough they are 'thick', 'stupid' or 'naughty' and they will believe it. It
becomes a self-fulfilling prophesy. Conversely, help them find their true potential, tell they CAN achieve
whatever they hope, and there is every chance they will.
Tomorrow I will tell you about the winter of '63 and my sporting achievements, (or rather the lack of
them), and badger watching, one of few opportunities to get out of bounds legitimately.

The winter of 1963 was cold. How cold? This is from Wikipedia.
"The winter of 1962–63, known as the Big Freeze of 1963, was one of the coldest winters on record in the
UK. Temperatures plummeted and lakes and rivers began to freeze over. In the temperature records
extending back to 1659, only the winters of 1683/4 and 1739/40 were colder than 1962–63."
It was cold, in fact the third coldest winter in the last 360 years.
Although life was disrupted massively, education continued unaffected, unlike the sporting activities.
300 plus teenage boys need to let of steam, and since the normal winter games of either rowing or
hockey the main alternatives were running, or a limited form of hockey played within the school
quadrangle.
I never liked running for running's sake and runs were often given as punishments by sub-prefects for
minor transgressions. This never bothered those who ran voluntarily. After they had fulfilled the required
distance they mocked the punishment giver by saying they were going to do that run anyway. Not a
good plan if the prefect had a good memory. Next time they might regret it.
So if you didn't like running and as a Rower, Quad Hockey was not an option, what else could you do to
fulfil the obligatory requirement to take some physical exercise every day? By great good fortune, the
father of one of my pals worked for Oxfam. They had just set up one of the first charity shops and he
came back to school with a pair of ancient ice skates. The kind you strap onto the bottom of a heavy
boot. My army boot, issued by the cadet force was ideal, so having roller-skated a lot at Great Walstead,
I took to ice skating on the frozen Kennet and Avon Canal as a natural, and have enjoyed ice skating
ever since.
The freeze continued for the entire term. On Wednesdays, we went out and about with the cadets,
walking on the frozen snow over the tops of mature hedges. Every night we walked up the hill to our
boarding house. In normal weather we walked up a local curiosity called a Drung. This was a footpath
going directly up the hillside, between two stone walls. When we first arrived back at the beginning of
term the Drung was packed with snow, so we walked up the field beside it, but as the snow between the
walls compacted we were able to come back down the hill by sliding down a narrow Cresta Run type
groove in the snow, one foot behind the other.
There were no serious accident caused by the freeze, but my classroom that year was in the old village
school. Part of the old playground was a steeply sloping path up to the toilets. We had fun by pouring
water onto the slope and sliding down the resulting ice sheet. That was dangerous enough for us who
knew it, but one afternoon a senior boy who was coming to police, sorry 'supervise' our prep
(homework) session, was caught unawares and had a nasty fall. He was not badly injured thankfully.
Not all of the senior boys fell into the mini-Hitler type of sub-prefect, full of their own self-importance
and power mad. Most were very decent and caring. In my time in Hill House there were a few boys senior
to me, all very clever and decent who went on to great things. Dearlove, became Sir Richard Dearlove,
when he was head of MI5. Stilgoe, became Sir Richard Stilgoe, the impresario well known for his musical
talents, first seen on Esther Ranzen's 'That's Life' programme, but the third was Bernard Wiggins. You
might not know that name, but may well have read some of his books. He is now known as Bernard

Cornwell, best selling author of the Sharpe series of novels. For a while he was my 'Dorm Senior' and a
good sport.
Monkton was good for me, and to me. Most of my friends would probably say the same. For me, it
offered a lot of freedom, but for one of my best friends, Richard Cooper, whose family were farming in
the Cotswolds, it was the opposite. He had a horse at home which he sorely missed and although he
never rebelled, he was not particularly happy there. I last saw him in Australia shortly before he died,
much too young.
The big freeze ended and the cricket and rugby pitches in the bottom of the valley flooded. Nothing
unusual there. That is nature, they are flood plains, just don't build houses on them!
Running up the valley was a disused railway line, known a Clank. Shortly before the line was ripped up it
was set for the 1953 comedy film The Titfield Thunderbolt, coincidentally just shown on BBC2 last week.
The cricket pitch, known as 'Longmead' was in the scene when all the players rushed to see the train
steaming by.
The following (summer) term we either played cricket, rowed and just a few played tennis. I rowed, and
whilst not particularly good, I was reasonably competent. We learned the fundamentals in 'The Tank' a
strange, recently completed contraption where the oarsmen sat on seats surrounded by the water. As
you rowed, you stayed still, but the water went round and round. Quite ingenious in fact.
Most of the boats were 'fours' with four oarsmen and the 'cox', a small boy with a loud voice tucked into
the stern steering the boat and shouting out the commands. The river Avon is too narrow for boats to
race side by side, so a clever form of racing is adopted instead. All the boats are spaced out equally
down the line of the river - pointing upstream. I forget the exact gap, but it is several boat lengths. Upon
starting, the aim of the exercise is to catch the boat in front and touch their stern with your bow. At that
point those two boats pull over to the side, so for the next race, normally the following day, the starting
positions are reversed.
The oar hanging up in my hall at home was won by my father rowing for his Oxford College, St. Edmund
Hall. (Teddy Hall) If you 'bumped' every day of race week, you were awarded your oar.
Regrettably my rowing career ended the following summer. I had realised that if I was to get my 'A' Level
I was going to have to work very hard indeed. I was never a natural academic, and Rowing took up too
much time. The teams went off for entire weekends to regattas scattered around the country, and whilst
no doubt great fun, I had seen too many of the successful sporty types come a cropper with their exams
so I decided to opt out and play tennis instead, just for fun and to get enough exercise. After all, you

could play tennis with just one other person, and perhaps, just perhaps, that person might be wearing a
skirt.
I had made the decision to stop in principle, but the actual moment when I stopped was prompted by a
silly petty decision by the senior boy coaching our crew on the day in question. The walk from the
school to riverside boat house took about twenty minutes. We were meant to arrive five minutes before
the official start time of the 'outing' to ensure there was no delay. On the day in question one or two of
us arrived exactly on time, just as our boat was being disembarked by the earlier crew. The coach said
"You should have been here five minutes ago. There's no outing today!" Strictly speaking he was within
his rights to do that, but I suspected it was an excuse not to have to take us out that day. I also felt he
could have punished the offenders in a number of other ways, but for me that was enough, and I told my
tutor what had happened and how, for the sake of my 'A' Levels, I should give up rowing.

History proved that I made the right decision, but that day also coloured my attitude towards authority. I
still think the spirit of the law is more important that the letter of the law - within reason! Respect
everyone.
