# Gun Games with the CCF

I mentioned in passing earlier the CCF, the Combined Cadet Force. In many Public Schools there was, perhaps
still is, a strong link with military. When I doing my PGCE, the grand sounding 'Post Graduate Certificate in
Education', at Reading University, I did my teaching practice at Wellington College. The name alone suggests
military connection, so even Monkton, set up to educate the sons of Christian Missionaries, had its CCF.
There is the expression, 'If you can't beat them, join them' so although theoretically one might have been able to
opt out, in practice no one did. It was all rather gung ho. 'Jolly good fun chaps, this army lark!' Looking back it
was frighteningly like the 'Oh Oh Oh What a Lovely War' attitude which prevailed at the outbreak of World War 1.
Training, on Wednesday afternoons, started with Square Bashing, or Drill. Itchy Battledress uniforms, spit and
polish, literally, of the boot's toe caps, and being yelled at by the Sergeants, many of whom were the dreaded
Sub-Prefects, but now with three stripes on their arms. It was amazing how soon we resembled a moderately
competent fighting force. Drill required a degree of coordinating, and if you didn't have it already, you soon did if
you didn't want to be given even more punishments.
I can still hear the words "STOP T L V RETURN" ringing in my ears. They are the commands for the About Turn
on the march, with the T, L and the V representing the position of your feet. It was a brutal form of choreography,
but nevertheless quite satisfying when you got it right.
Highlights of the CCF year were the Field Days on Salisbury Plain. We were issued with 'Blanks' and played
"Gun Games' with great enthusiasm and lots of noise around the spookily deserted village of Imber. The village
had been taken over years earlier for Army training, much to the fury of its inhabitants who had always hoped to
get their homes back.
In the Summer holidays we were sent off to 'Camp' for two weeks, to one of the regular army training areas such
as Lympstone in Devon, home of the Royal Marines. We engaged in exercises involving landing craft, assault
courses and life in tents, which were inspected every morning for the precision with which your bed, pillow and
kit was laid out. Generally good fun was had by all, unless you happened to be one of the nastier sergeants who,
when making a real dog's dinner of an obstacle on the assault course was given a professional bollocking by a
regular soldier, much to our satisfaction and amusement.
Back at school, trips to the rifle range near Box Hill were popular, perhaps more for the wall paper adorning the
rangemaster's cabin than the prospects of becoming a Marksman. I was quite a good shot and remember with
pride the day I was given my cloth Marksman's rifle which I sewed onto the sleeve of my battledress.
You will have picked up that I quite enjoyed the CCF. This was partly because during my second year, a more
enlightened attitude prevailed, so instead of concentrating exclusively on Infantry training to the exclusion of
everything else, new sections were started. The MT section, or Motor Transport, acquired and old car engine we
stripped down and learned all the parts. By now, even I had been promoted so with my three Sergeant's stripes I
was put in charge of the new Civil Defence section. This involved a journey into Bath where we learned to set up
Field Kitchens with their Earth Ovens to feed the nation in the event of a Nuclear War.
One week we were shown a film which chillingly told us that we only had four minutes warning from the time the
missiles were launched to the moment of impact. The next week, after the training we waited to board the army
truck which would take us back to school. There was a problem with the garage door, but eventually, after
SEVEN minutes, it was prised open. Not a good omen for our survival. It was very much along the lines of Dad's
Army and a sense of humour helped get us through.
To put this period in context, there had been the First World War; we had been born just after the end of the
Second World War, and with all of the nuclear proliferation, the Third World War just seemed to be a matter of
when, not if. It was a scary time. We had the Cuban Missile Crisis, when the world held its breath, and we can
remember exactly where we were when we heard that President Kennedy had been assassinated.
My early musical career was short lived. I couldn't master the Violin. I took one home to practice in holidays, but
all I made was a vile din, so that went nowhere. I only briefly joined the choral society. The attraction of this
society was an annual joint concert with the girls of Westonbirt school, but when the conductor waved his baton
in a circular motion saying "There is someone singing out of tune around here" I knew I was in the centre of his
circle, so I opted out of that too.

However, my musical career took an unexpected turn when a Military Band was set up to play at the CCF's
annual inspection. The first instruments to appear were bugles. I was able to make a reasonably rendition of the
Last Post, or Come to the Cookhouse Door, but then a number of side drums appeared. That was much more
my cup of tea, so I learned to do a drum roll with the drum sticks.
When the band itself was formed there were plenty of volunteers from the competent musicians within the
orchestra, but playing while marching was a challenge. The first afternoon we were told not to worry about
keeping in step, just try to play while walking. Cacophony. Gradually things improved and by the end of the year
the CCF staged a flood lit military tattoo, when the Band of the Black Watch accompanied us.
What I have not told you was the 'instrument' I ended up with. I played the cymbals! With great gusto and no
complaints.
Next time I will explore the unexpected link between army training and natural history. The two photographs I
posted today are relevant, and are there for you to think about before I explain tomorrow.

The six S's and the motorbike.
Unlocking memories from the distant past.
One of the things I have found most enjoyable writing up my memories has been how by recollecting one
particular event has reawakened the memory of another incident I had not thought about for more than half a
century.
'Spit and Polish' was, and probably still is, quite literally how soldiers get an amazing mirror like finish on the toe
caps of their boots. You get a cloth, add boot polish, then rubbing gently round and round for hours, adding spit
from time to time. In time an incredible glass like surface starts to form.
In the weeks leading up to the CCF's annual inspection countless hours were spent (wasted?) on bringing our
boots up to that standard. The problem was, just as you reached perfection it could all go disastrously wrong and
the surface would disintegrate. This happened to one of my pals just before the big day. What to do? He took a
gamble and painted the toe caps with gloss black paint. The inspecting VIP commended him on the high
standard of his boots. Another candidate for SpecSavers?
Yesterday I posted two photographs of Roe bucks with my story and said I would explain their relevance today. I
wonder if anyone has guessed the connection?
Let me explain. One of the topics covered in the army cadet training was Fieldcraft, and in particular how
sentries or patrols can learn to hide from view using camouflage and concealment techniques.
A particular mnemonic was used to teach this - THE SIX S's.
Had I not looked it up, I would never have spelled mnemonic correctly. I would have started it with pneu....., but
thanks to my friend Mr. Google, I can explain what a pneumonic, sorry, a mnemonic is.....
I. What is a Mnemonic?
A mnemonic, also known as a memory aid, is a tool that helps you remember an idea or phrase with a pattern of
letters, numbers, or relatable associations. Mnemonic devices include special rhymes and poems, acronyms,
images, songs, outlines, and other tools. Mnemonic (pronounced ni-mon-ik) is derived from the Greek phrase
mimnēskesthai meaning to “remember.”
So now you know!
In teaching these concealment techniques 'The six S's' were Shape, Shadow, Shine, Silhouette, Surface and
....., well we used the word SHIFT for 'movement'.
I wondered if Google would reveal anything about this concept and to my surprise I unearthed a current Power
Point presentation used to aid field craft training. The teaching technology has moved on, but the basic message
is exactly the same, and it is the principles of concealment in nature which I love. That is why I posted the two
deer pictures yesterday.

The younger buck, whose antlers are still covered in velvet, is standing right on the ridge, clearly silhouetted
against the sky. The older buck is standing stock still in the shadow of a bush. (Can you see how his antlers
have no velvet on them - he'll soon need to use them in earnest this year to fight off rivals who have their eyes
on his ladies, so he has to have his antlers ready for action sooner than the young buck, whose antlers won't be
needed for action for a year or two.)
The other side of the concealment techniques, are the observational skills you need to develop if you are going
to spot creatures (or sentries) who are trying not to be seen.
One year a fox had her family in a den high up on the opposite side of the river but I could get a good view of it
by climbing to the same level on our side of the river. The flat stump of a recently felled tree gave me a good
seat, so armed with my binoculars, I took up a pad of paper to write letters while waiting for the action to start.
On very still evening I was sure I had seen a movement below me. I then saw it again. When I checked it out I
could see a deer's ear. It was attached to the deer, but that was all I could see of the animal, but flies were
bothering it and the ear kept twitching.
The Monkton Combe valley below the school had an attractive stream, known as the Midford Brook. Although
there were trout in the brook, I more often fished for Dace, small coarse fish which shoaled at one particular
spot. One of the masters was a keen angler who took us to a nearby lake teeming with perch of which we caught
plenty. This was a marked contrast with a funny incident on the canal. Richard Cooper (my friend was from the
farm in Burford) and I were walking on the canal tow path when we saw a large perch lying still in the water. Just
further up a couple were fishing, but they had had no luck, so we told them about the fish we had just seen. The
chap pulled up the pathetic drowned worm, purporting to be the bait, and lowered it right in front of the perch's
nose. Not only was the fish totally uninterested, it didn't even move away. Had I been that angler I think I would
have given up.
I want to tell you about badger watching, bird watching and barbed wire, but I will finish today with a story of the
motorbike.
My cousin Judith had joined the staff of Monkton Combe's junior school on Combe Down, just a couple of miles
up the hill. Richard Cooper and I were having tea with her one Sunday afternoon when she told me about a
motorbike one of the teachers had. It was a James Cadet, but the engine's big end, whatever that was, had
broken and he wanted rid of the bike. I had been in the MT section of the CCF the year before so I was keen to
take it apart to learn more about engines. To my surprise my House Master, Vic Baker allowed me to put the bike
into his garage, so we pushed the bike down the hill and removed the engine which I hid under the desk in the
study I shared with Richard Cooper.
We stripped the engine down, found the broken con rod, the bit which connects the piston to the cam shaft, and
ordered a new one. When the replacement arrived we reassembled the engine and everything seemed to fit
back into place. But would it work? To find out we needed petrol, so armed with a screw top jam jar we walked
down to the garage on the Warminster road and were given enough petrol to test is. I think you could actually
buy 2-stroke petrol from the garage, because that is what it needed.
That evening, during the 'Study Period' when we should have been doing our 'Prep' we got engine out from
under the desk, poured some petrol into the fuel pipe, and with Richard putting all his weight on the bare engine
block, I jumped on the kick start. To our horror, at the very first attempt the wretched engine burst into life. With
no silencer the racket was dreadful so I immediately whipped off the spark plug and we stuffed the engine back
under the desk.
As we did so, stomping up the corridor, a prefect was opening the other study doors. "What was that noise?
What was that noise?" I don't think playing the innocent card and asking "What noise?" cut much ice, but luckily
he was one of the decent Prefects and after explaining our project was with Mr. Baker's approval, we got away
with it. Not all of the prefects were mean. Brother David was known to be very fair, and went on to have a
distinguished career in the Police.
The engine and frame were reunited. We test ran the bike up and down the drive behind Hill House, and
eventually the bike made its way to London. I even passed my driving test on it before getting a Honda 90 to
commute from home to college.
Keep safe every one.
